<x-layouts.public-site :settings="$settings" :site-name="$siteName" :legal-name="$legalName" :navigation="$navigation" :chrome="$chrome" :page-title="data_get($homepage, 'settings.title', $pageTitle)" :description="data_get($homepage, 'settings.description', $description)" :canonical="$canonical" :robots="$preview ? 'noindex, nofollow' : 'index, follow'" :image="data_get($homepage, 'settings.og_image_path') ? asset(data_get($homepage, 'settings.og_image_path')) : null">
    @if($preview)<div class="sticky top-0 z-50 bg-amber-300 px-4 py-3 text-center text-sm font-bold text-amber-950" role="status">Preview Mode — draft content is visible only to active administrators.</div>@endif
    @if(! $homepage)
        <section class="bg-public-navy py-24 text-white sm:py-32"><div class="public-container max-w-3xl text-center"><p class="public-eyebrow text-blue-200">{{ $siteName }}</p><h1 class="mt-4 text-4xl font-bold tracking-tight sm:text-5xl">Website content is being prepared</h1><p class="mt-5 text-lg leading-8 text-slate-200">Please check back soon.</p></div></section>
    @else
        @foreach($homepage['sections'] as $section)
            @continue(! $preview && ! $section['enabled'])
            @if($section['key'] === 'hero')
                @php($slides = $section['items'])
                @if(count($slides))<section class="relative overflow-hidden bg-public-navy py-20 text-white sm:py-28" x-data="{ active: 0, count: {{ count($slides) }}, previous() { this.active = (this.active - 1 + this.count) % this.count }, next() { this.active = (this.active + 1) % this.count } }" x-on:keydown.left.window="previous()" x-on:keydown.right.window="next()" aria-roledescription="carousel" aria-label="Homepage highlights">
                    <div class="public-container">@foreach($slides as $index => $item)<article x-show="active === {{ $index }}" @if($index) x-cloak @endif aria-roledescription="slide" aria-label="Slide {{ $index + 1 }} of {{ count($slides) }}" class="grid items-center gap-10 lg:grid-cols-2"><div><p class="public-eyebrow text-blue-200">{{ $item['eyebrow'] ?: data_get($homepage, 'settings.eyebrow') }}</p><h1 class="mt-4 text-4xl font-bold tracking-tight sm:text-6xl">{{ $item['title'] }}</h1>@if($item['description'])<p class="mt-6 max-w-2xl text-lg leading-8 text-slate-200">{{ $item['description'] }}</p>@endif<div class="mt-8 flex flex-wrap gap-3">@if($item['primary_cta'])<x-public.button :href="$item['primary_cta']['url']" variant="light">{{ $item['primary_cta']['label'] }}</x-public.button>@endif @if($item['secondary_cta'])<x-public.button :href="$item['secondary_cta']['url']" variant="outline-dark">{{ $item['secondary_cta']['label'] }}</x-public.button>@endif</div></div>@if($item['image_path'])<x-public.image :src="asset($item['image_path'])" :alt="$item['image_alt']" aspect="aspect-[4/3]" loading="eager" fetchpriority="high" class="rounded-public" />@endif</article>@endforeach
                    @if(count($section['tabs']) > 1)<div class="mt-8 flex flex-wrap gap-2" role="tablist" aria-label="Hero categories" x-data="{ tab: 0 }">@foreach($section['tabs'] as $tabIndex => $tab)<button type="button" role="tab" :aria-selected="(tab === {{ $tabIndex }}).toString()" aria-controls="hero-tab-panel-{{ $tab['id'] }}" x-on:click="tab = {{ $tabIndex }}" class="min-h-11 rounded-md border border-white/40 px-4 focus-visible:ring-2 focus-visible:ring-white">{{ $tab['label'] }}</button><span id="hero-tab-panel-{{ $tab['id'] }}" role="tabpanel" x-show="tab === {{ $tabIndex }}" class="w-full text-sm text-slate-200">{{ $tab['description'] }}</span>@endforeach</div>@endif
                    @if(count($slides) > 1)<div class="mt-8 flex gap-3"><button type="button" x-on:click="previous()" aria-label="Previous hero slide" class="min-h-11 rounded-md border border-white/40 px-4 font-semibold focus-visible:ring-2 focus-visible:ring-white">Previous</button><button type="button" x-on:click="next()" aria-label="Next hero slide" class="min-h-11 rounded-md border border-white/40 px-4 font-semibold focus-visible:ring-2 focus-visible:ring-white">Next</button><span class="sr-only" aria-live="polite" x-text="`Slide ${active + 1} of ${count}`"></span></div>@endif</div>
                </section>@endif
            @elseif($section['key'] === 'bottom_cta')
                @if($section['heading'])<x-public.cta :eyebrow="$section['eyebrow']" :heading="$section['heading']" :description="$section['description']" :variant="in_array($section['background'], ['navy', 'gradient']) ? ($section['background'] === 'navy' ? 'dark' : 'gradient') : 'light'">@if($section['primary_cta'])<x-slot:primary><x-public.button :href="$section['primary_cta']['url']" variant="light">{{ $section['primary_cta']['label'] }}</x-public.button></x-slot:primary>@endif @if($section['secondary_cta'])<x-slot:secondary><x-public.button :href="$section['secondary_cta']['url']" variant="outline-dark">{{ $section['secondary_cta']['label'] }}</x-public.button></x-slot:secondary>@endif</x-public.cta>@endif
            @elseif($section['key'] === 'about')
                <x-public.section :variant="$section['background'] === 'alternate' ? 'alternate' : 'standard'"><div class="grid items-center gap-10 lg:grid-cols-2"><div><x-public.section-heading alignment="left" :eyebrow="$section['eyebrow']" :title="$section['heading'] ?: 'About'" :description="$section['description']" />@if($section['secondary_description'])<p class="mt-5 leading-7 text-public-secondary">{{ $section['secondary_description'] }}</p>@endif</div>@if($section['image_path'])<x-public.image :src="asset($section['image_path'])" :alt="$section['image_alt']" aspect="aspect-[4/3]" class="rounded-public" />@endif</div></x-public.section>
            @else
                <x-public.section :variant="$section['background'] === 'alternate' ? 'alternate' : 'standard'">
                    <x-public.section-heading :eyebrow="$section['eyebrow']" :title="$section['heading'] ?: str($section['key'])->replace('_', ' ')->title()" :description="$section['description']" />
                    @if($section['key'] === 'faq')<div class="mx-auto mt-10 grid max-w-3xl gap-3">@foreach($section['items'] as $item)<div x-data="{ open: false }" class="rounded-public border border-public-border bg-white"><h3><button type="button" class="flex min-h-14 w-full items-center justify-between gap-4 px-5 text-left font-semibold focus-visible:ring-2 focus-visible:ring-public-focus" x-on:click="open = !open" :aria-expanded="open.toString()" aria-controls="faq-panel-{{ $item['id'] }}"><span>{{ $item['title'] }}</span><span aria-hidden="true">+</span></button></h3><div id="faq-panel-{{ $item['id'] }}" x-show="open" x-cloak class="px-5 pb-5 leading-7 text-public-secondary">{{ $item['description'] }}</div></div>@endforeach</div>
                    @elseif($section['key'] === 'statistics')<div class="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">@foreach($section['items'] as $item)<div class="rounded-public border border-public-border bg-white p-6 text-center"><p class="text-4xl font-bold text-public-navy">{{ $item['prefix'] }}{{ $item['value'] }}{{ $item['suffix'] }}</p><h3 class="mt-2 font-semibold">{{ $item['title'] }}</h3>@if($item['description'])<p class="mt-2 text-sm text-public-secondary">{{ $item['description'] }}</p>@endif</div>@endforeach</div>
                    @else<x-public.grid columns="3" class="mt-10">@foreach($section['items'] as $item)<x-public.card variant="feature" :title="$item['title']" :description="$item['description']">@if($item['image_path'])<x-slot:icon><x-public.image :src="asset($item['image_path'])" :alt="$item['image_alt']" aspect="aspect-video" /></x-slot:icon>@endif @if($item['canonical_solution'])<x-slot:action><a class="font-semibold text-public-primary" href="{{ $item['canonical_solution']['url'] }}">Explore solution</a></x-slot:action>@elseif($item['organization'])<x-slot:action><span class="text-sm font-semibold text-public-secondary">{{ $item['organization'] }}</span></x-slot:action>@endif</x-public.card>@endforeach</x-public.grid>@endif
                </x-public.section>
            @endif
        @endforeach
    @endif
</x-layouts.public-site>
