<?php
use App\Domain\Capabilities\{CapabilityManager,CapabilityRegistry}; use App\Models\{Capability,CapabilityCategory,User,WebsiteSetting}; use Illuminate\Foundation\Testing\RefreshDatabase;
uses(RefreshDatabase::class);
beforeEach(function(){file_put_contents(storage_path('app/installed'),now()->toIso8601String());WebsiteSetting::query()->create(['site_name'=>'Test','site_url'=>'https://example.test','timezone'=>'Africa/Lagos']);});afterEach(fn()=>@unlink(storage_path('app/installed')));
function capability(array $overrides=[]):Capability{return Capability::query()->create(array_merge(['title'=>'Cloud delivery','slug'=>'cloud-delivery','short_description'=>'Configured factual capability.','template'=>'standard','hero_style'=>'standard','status'=>'draft','display_order'=>1],$overrides));}
it('requires authentication for capability administration',fn()=>$this->get('/content/capabilities')->assertRedirect());
it('allows anonymous index access',fn()=>$this->get('/capabilities')->assertSuccessful());
it('hides private capability lifecycle states',function(string $status,array $dates){$item=capability(['status'=>$status]+$dates);$this->get(route('capabilities.show',$item->slug))->assertNotFound();})->with(['draft'=>['draft',[]],'future schedule'=>['scheduled',['scheduled_for'=>now()->addDay()]],'archived'=>['archived',['archived_at'=>now()]]]);
it('renders published and due scheduled capabilities',function(string $status,array $dates){$item=capability(['status'=>$status]+$dates);$this->get(route('capabilities.show',$item->slug))->assertSuccessful()->assertSeeText('Cloud delivery');})->with(['published'=>['published',['published_at'=>now()]],'due schedule'=>['scheduled',['scheduled_for'=>now()->subMinute()]]]);
it('normalizes and uniquely duplicates capability slugs and children',function(){$item=capability();$item->highlights()->create(['title'=>'Delivery','description'=>'Exact text','display_order'=>1]);$copy=app(CapabilityManager::class)->duplicate($item,User::factory()->create()->id);expect($copy->slug)->toBe('cloud-delivery-copy')->and($copy->status)->toBe('draft')->and($copy->highlights)->toHaveCount(1);});
it('publishes unpublishes archives and restores without losing content',function(){$item=capability();$manager=app(CapabilityManager::class);$manager->publish($item);expect($item->refresh()->published_at)->not->toBeNull();$manager->unpublish($item);expect($item->refresh()->short_description)->toBe('Configured factual capability.');$manager->archive($item);expect($item->refresh()->archived_at)->not->toBeNull();$manager->restore($item);expect($item->refresh()->status)->toBe('draft');});
it('enforces capability category restrictive deletion',function(){$category=CapabilityCategory::create(['name'=>'Technical','slug'=>'technical','display_order'=>1]);capability(['capability_category_id'=>$category->id]);expect(fn()=>$category->delete())->toThrow(Throwable::class);});
it('defines fixed templates hero styles child limits and reserved slugs',function(){expect(CapabilityRegistry::TEMPLATES)->toContain('technical')->and(CapabilityRegistry::HERO_STYLES)->toBe(['standard','split','dark','gradient'])->and(CapabilityRegistry::CHILDREN)->toBe(['highlights'=>12,'benefits'=>12,'facts'=>8])->and(CapabilityRegistry::RESERVED)->toContain('preview');});
it('previews drafts privately with noindex headers',function(){$user=User::factory()->create(['is_active'=>true]);$item=capability();$this->actingAs($user)->get(route('admin.capabilities.preview',$item))->assertSuccessful()->assertHeader('X-Robots-Tag','noindex, nofollow')->assertSeeText('Preview Mode');});
it('adds only visible indexable capabilities to sitemap',function(){$visible=capability(['status'=>'published','published_at'=>now()]);capability(['slug'=>'private','robots_index'=>false]);$this->get('/sitemap.xml')->assertSee('/capabilities/'.$visible->slug)->assertDontSee('/capabilities/private');});
