<x-layouts.app title="Media Library" :breadcrumbs="[['label'=>'Content'],['label'=>'Media Library']]" data-noindex>
<div class="space-y-6 p-4 sm:p-6" x-data="{dragging:false}">
 <x-admin.page-header title="Media Library" description="Secure canonical raster images and favicons. Archived assets remain available to existing content." />
 <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_22rem]">
  <main class="space-y-5">
   <x-admin.card><form method="GET" class="grid gap-3 sm:grid-cols-2 lg:grid-cols-5" role="search"><x-admin.form-input name="search" label="Search" :value="$filters['search']??''"/><x-admin.select name="type" label="Type" :options="[''=>'All types','image'=>'Images','favicon'=>'Favicons']" :selected="$filters['type']??''"/><x-admin.select name="status" label="Status" :options="['active'=>'Active','archived'=>'Archived','all'=>'All']" :selected="$filters['status']??'active'"/><x-admin.select name="collection" label="Collection" :options="[''=>'All collections']+$collections->pluck('name','id')->all()" :selected="$filters['collection']??''"/><x-admin.select name="sort" label="Sort" :options="['newest'=>'Newest','oldest'=>'Oldest','title'=>'Title','size'=>'Size']" :selected="$filters['sort']??'newest'"/><div><x-admin.primary-button>Apply filters</x-admin.primary-button></div></form></x-admin.card>
   @if($assets->count())<div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3" aria-label="Media results">@foreach($assets as $asset)<a href="{{ route('admin.media.show',$asset['uuid']) }}" class="group rounded-xl border border-slate-200 bg-white p-3 shadow-sm focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 dark:border-slate-700 dark:bg-slate-900"><div class="aspect-video overflow-hidden rounded-lg bg-slate-100 dark:bg-slate-800">@if($asset['url'])<img src="{{ $asset['url'] }}" alt="{{ $asset['alt'] ?: 'Preview of '.$asset['title'] }}" width="{{ $asset['width'] }}" height="{{ $asset['height'] }}" loading="lazy" class="h-full w-full object-contain">@else<div class="grid h-full place-items-center text-sm">File unavailable</div>@endif</div><h2 class="mt-3 truncate font-semibold">{{ $asset['title'] }}</h2><p class="mt-1 text-sm text-slate-600 dark:text-slate-300">{{ $asset['width'] }}×{{ $asset['height'] }} · {{ Number::fileSize($asset['size']) }}</p><p class="mt-1 text-xs">{{ ucfirst($asset['type']) }} · {{ ucfirst($asset['status']) }} · Used {{ $asset['usages_count'] }} time(s)</p></a>@endforeach</div><div>{{ $assets->links() }}</div>@else<x-admin.empty-state title="No media found" description="Upload an approved raster image or change the filters."/>@endif
  </main>
  <aside class="space-y-5"><x-admin.card><h2 class="text-lg font-bold">Upload media</h2><form method="POST" action="{{ route('admin.media.store') }}" enctype="multipart/form-data" class="mt-4 space-y-4" @dragover.prevent="dragging=true" @dragleave.prevent="dragging=false" @drop="dragging=false">@csrf<label for="media-file" class="block rounded-lg border-2 border-dashed p-5 text-center" :class="dragging?'border-blue-600':'border-slate-300'"><span class="font-medium">Choose or drop one image</span><span class="mt-1 block text-xs">JPG, PNG, WebP up to 8 MB; favicon PNG/ICO up to 1 MB. 16–8000px, max 40 MP.</span></label><input id="media-file" name="file" type="file" accept=".jpg,.jpeg,.png,.webp,.ico,image/jpeg,image/png,image/webp,image/x-icon" required class="block w-full text-sm"><x-admin.select name="media_type" label="Purpose" :options="['image'=>'Website image','favicon'=>'Favicon']"/><x-admin.checkbox name="allow_duplicate" label="Allow an intentional duplicate"/><x-admin.primary-button>Upload securely</x-admin.primary-button></form></x-admin.card>
  <x-admin.card><h2 class="text-lg font-bold">Collections</h2><p class="mt-1 text-sm">Logical organization only; collections never change storage paths.</p><form method="POST" action="{{ route('admin.media.collections.store') }}" class="mt-4 space-y-3">@csrf<x-admin.form-input name="name" label="New collection name"/><x-admin.primary-button>Create collection</x-admin.primary-button></form></x-admin.card></aside>
 </div>
</div>
</x-layouts.app>
