<?php
use App\Domain\WorkProcesses\{WorkProcessManager,WorkProcessRegistry}; use App\Models\{User,WebsiteSetting,WorkProcess}; use Illuminate\Foundation\Testing\RefreshDatabase;
uses(RefreshDatabase::class);
beforeEach(function(){file_put_contents(storage_path('app/installed'),now()->toIso8601String());WebsiteSetting::query()->create(['site_name'=>'Test','site_url'=>'https://example.test','timezone'=>'UTC']);});afterEach(fn()=>@unlink(storage_path('app/installed')));
function processItem(array $overrides=[]):WorkProcess{$item=WorkProcess::query()->create(array_merge(['title'=>'Delivery process','slug'=>'delivery-process','short_description'=>'Configured process.','template'=>'standard','hero_style'=>'standard','status'=>'draft','display_order'=>1],$overrides));return $item;}
it('requires authentication for process administration',fn()=>$this->get('/content/work-processes')->assertRedirect());it('allows anonymous process index',fn()=>$this->get('/work-processes')->assertSuccessful());
it('enforces public process lifecycle visibility',function(string $status,array $dates,bool $visible){$item=processItem(['status'=>$status]+$dates);$response=$this->get(route('work-processes.show',$item->slug));$visible?$response->assertSuccessful():$response->assertNotFound();})->with(['draft'=>['draft',[],false],'future'=>['scheduled',['scheduled_for'=>now()->addDay()],false],'due'=>['scheduled',['scheduled_for'=>now()->subMinute()],true],'published'=>['published',['published_at'=>now()],true],'archived'=>['archived',['archived_at'=>now()],false]]);
it('derives stage numbering from ordered stages and renders deliverables',function(){$item=processItem(['status'=>'published','published_at'=>now()]);$stage=$item->stages()->create(['title'=>'Discover','description'=>'Understand needs','display_order'=>1,'is_active'=>true]);$stage->deliverables()->create(['title'=>'Discovery report','display_order'=>1,'is_active'=>true]);$this->get(route('work-processes.show',$item->slug))->assertSeeText('1. Discover')->assertSeeText('Discovery report');});
it('duplicates stages and deliverables but clears lifecycle state',function(){$item=processItem(['status'=>'published','published_at'=>now()]);$stage=$item->stages()->create(['title'=>'Discover','description'=>'Needs','display_order'=>1]);$stage->deliverables()->create(['title'=>'Report','display_order'=>1]);$copy=app(WorkProcessManager::class)->duplicate($item,User::factory()->create()->id);expect($copy->status)->toBe('draft')->and($copy->published_at)->toBeNull()->and($copy->stages)->toHaveCount(1)->and($copy->stages->first()->deliverables)->toHaveCount(1);});
it('requires an active stage before publishing',function(){$item=processItem();expect(fn()=>app(WorkProcessManager::class)->publish($item))->toThrow(Illuminate\Validation\ValidationException::class);});
it('defines bounded stages deliverables templates heroes and icons',function(){expect(WorkProcessRegistry::MAX_STAGES)->toBe(12)->and(WorkProcessRegistry::MAX_DELIVERABLES)->toBe(8)->and(WorkProcessRegistry::TEMPLATES)->toContain('timeline')->and(WorkProcessRegistry::HERO_STYLES)->toContain('gradient')->and(WorkProcessRegistry::ICONS)->not->toBeEmpty();});
it('previews draft process with private noindex headers',function(){$user=User::factory()->create(['is_active'=>true]);$item=processItem();$this->actingAs($user)->get(route('admin.work-processes.preview',$item))->assertSuccessful()->assertHeader('X-Robots-Tag','noindex, nofollow')->assertSeeText('Preview Mode');});
it('sitemap includes visible process and excludes private process',function(){$visible=processItem(['status'=>'published','published_at'=>now()]);processItem(['slug'=>'private']);$this->get('/sitemap.xml')->assertSee('/work-processes/'.$visible->slug)->assertDontSee('/work-processes/private');});
