<?php
namespace App\Domain\Solutions;
use App\Models\{Solution,SolutionCategory}; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str; use Illuminate\Validation\ValidationException;
final class SolutionManager
{
 public function save(array $data,?Solution $solution,int $userId):Solution{return DB::transaction(function()use($data,$solution,$userId){$solution??=new Solution;$data['updated_by']=$userId;if(!$solution->exists){$data['created_by']=$userId;$data['status']='draft';$data['display_order']=(int)Solution::max('display_order')+1;}else{unset($data['status']);}$solution->fill($data)->save();$this->normalize();return $solution;});}
 public function publish(Solution $s):void{$this->requireContent($s);DB::transaction(fn()=>$s->update(['status'=>'published','published_at'=>now(),'scheduled_for'=>null,'archived_at'=>null]));} public function schedule(Solution $s,string $utc):void{$this->requireContent($s);$s->update(['status'=>'scheduled','scheduled_for'=>$utc,'published_at'=>null,'archived_at'=>null]);} public function unpublish(Solution $s):void{$s->update(['status'=>'draft','published_at'=>null,'scheduled_for'=>null,'archived_at'=>null]);}
 public function archive(Solution $s):void{$d=app(SolutionDependencyInspector::class)->inspect($s);if($d['blocked'])throw ValidationException::withMessages(['solution'=>'Resolve active navigation, homepage, and incoming solution references before archiving.']);$s->update(['status'=>'archived','archived_at'=>now(),'published_at'=>null,'scheduled_for'=>null]);} public function restore(Solution $s):void{$s->update(['status'=>'draft','archived_at'=>null,'published_at'=>null,'scheduled_for'=>null]);}
 public function duplicate(Solution $s,int $userId):Solution{return DB::transaction(function()use($s,$userId){$copy=$s->replicate(['status','published_at','scheduled_for','archived_at','created_by','updated_by']);$copy->title.=' (Copy)';$copy->slug=$this->uniqueSlug($s->slug.'-copy');$copy->status='draft';$copy->published_at=$copy->scheduled_for=$copy->archived_at=null;$copy->created_by=$copy->updated_by=$userId;$copy->display_order=(int)Solution::max('display_order')+1;$copy->save();foreach(['features','benefits','capabilities','processSteps','useCases'] as $relation){$s->{$relation}()->each(fn($child)=>$copy->{$relation}()->create($child->only($child->getFillable())));}return $copy;});}
 public function move(Solution $s,string $direction):void{DB::transaction(function()use($s,$direction){$peer=Solution::where('display_order',$direction==='up'?'<':'>',$s->display_order)->orderBy('display_order',$direction==='up'?'desc':'asc')->first();if($peer){$a=$s->display_order;$s->update(['display_order'=>$peer->display_order]);$peer->update(['display_order'=>$a]);}$this->normalize();});}
 public function uniqueSlug(string $base):string{$base=Str::slug(Str::lower($base))?:'solution';$slug=$base;for($i=2;Solution::where('slug',$slug)->exists();$i++)$slug=Str::limit($base,150,'')."-$i";return $slug;} private function normalize():void{Solution::orderBy('display_order')->orderBy('id')->get()->each(fn($s,$i)=>$s->display_order===$i+1?null:$s->updateQuietly(['display_order'=>$i+1]));} private function requireContent(Solution $s):void{if(!trim($s->title)||!trim($s->short_description))throw ValidationException::withMessages(['solution'=>'A title and short description are required before publication.']);}
 public function saveCategory(array $data,?SolutionCategory $category=null):SolutionCategory{return DB::transaction(function()use($data,$category){$category??=new SolutionCategory;if(!$category->exists)$data['display_order']=(int)SolutionCategory::max('display_order')+1;$category->fill($data)->save();$this->normalizeCategories();return $category;});} public function moveCategory(SolutionCategory $c,string $direction):void{DB::transaction(function()use($c,$direction){$p=SolutionCategory::where('display_order',$direction==='up'?'<':'>',$c->display_order)->orderBy('display_order',$direction==='up'?'desc':'asc')->first();if($p){$a=$c->display_order;$c->update(['display_order'=>$p->display_order]);$p->update(['display_order'=>$a]);}$this->normalizeCategories();});} private function normalizeCategories():void{SolutionCategory::orderBy('display_order')->orderBy('id')->get()->each(fn($c,$i)=>$c->display_order===$i+1?null:$c->updateQuietly(['display_order'=>$i+1]));}
}
