<?php
namespace App\Domain\Solutions;
use App\Domain\PublicChrome\{PublicAssetPath,PublicLink}; use App\Models\Solution; use Illuminate\Support\Facades\Cache; use Throwable;
final class SolutionViewData
{
 public function published(string $slug):?array{try{$s=Solution::publiclyVisible()->where('slug',$slug)->first();if(!$s)return null;return Cache::remember("public.solutions.v1.$s->id.$slug.".SolutionCache::version($s->id),now()->addMinutes(15),fn()=>$this->transform($this->load($s),false));}catch(Throwable){return $this->direct($slug);}}
 public function preview(Solution $s):array{return $this->transform($this->load($s),true);} private function load(Solution $s):Solution{return $s->load(['category','features'=>fn($q)=>$q->orderBy('display_order')->limit(12),'benefits'=>fn($q)=>$q->orderBy('display_order')->limit(12),'capabilities'=>fn($q)=>$q->orderBy('display_order')->limit(12),'processSteps'=>fn($q)=>$q->orderBy('display_order')->limit(8),'useCases'=>fn($q)=>$q->orderBy('display_order')->limit(12),'relatedSolutions'=>fn($q)=>$q->publiclyVisible()->limit(6),'relatedPages'=>fn($q)=>$q->publiclyVisible()->limit(6)]);}
 private function transform(Solution $s,bool $preview):array{$children=fn($values)=>$values->filter(fn($v)=>$preview||$v->is_active)->map(fn($v)=>['title'=>$v->title,'description'=>$v->description,'sector'=>$v->sector??null,'icon'=>in_array($v->icon,SolutionRegistry::ICONS,true)?$v->icon:null])->values()->all();return ['id'=>$s->id,'title'=>$s->title,'slug'=>$s->slug,'eyebrow'=>$s->eyebrow,'short_description'=>$s->short_description,'overview'=>$s->overview,'challenge'=>$s->challenge_text,'approach'=>$s->approach_text,'outcome'=>$s->outcome_text,'icon'=>in_array($s->icon,SolutionRegistry::ICONS,true)?$s->icon:null,'image'=>PublicAssetPath::isSafe($s->featured_image_path)?$s->featured_image_path:null,'image_alt'=>$s->featured_image_alt,'hero_style'=>in_array($s->hero_style,SolutionRegistry::HERO_STYLES,true)?$s->hero_style:'standard','template'=>in_array($s->template,SolutionRegistry::TEMPLATES,true)?$s->template:'standard','category'=>$s->category&&$s->category->is_active?['name'=>$s->category->name,'slug'=>$s->category->slug]:null,'features'=>$children($s->features),'benefits'=>$children($s->benefits),'capabilities'=>$children($s->capabilities),'process'=>$children($s->processSteps),'use_cases'=>$children($s->useCases),'related_solutions'=>$s->relatedSolutions->map(fn($r)=>['title'=>$r->title,'description'=>$r->short_description,'url'=>route('solutions.show',$r->slug)])->all(),'related_pages'=>$s->relatedPages->map(fn($p)=>['title'=>$p->title,'url'=>route('pages.show',$p->slug)])->all(),'primary_cta'=>$this->link($s->primary_cta_label,$s->primary_cta_url),'secondary_cta'=>$this->link($s->secondary_cta_label,$s->secondary_cta_url),'meta_title'=>$s->meta_title?:$s->title,'meta_description'=>$s->meta_description?:$s->short_description,'og_title'=>$s->og_title?:($s->meta_title?:$s->title),'og_description'=>$s->og_description?:($s->meta_description?:$s->short_description),'og_image'=>PublicAssetPath::isSafe($s->og_image_path)?$s->og_image_path:null,'canonical_url'=>$s->canonical_url,'robots'=>$preview?'noindex, nofollow':(($s->robots_index?'index':'noindex').', '.($s->robots_follow?'follow':'nofollow')),'updated_at'=>$s->updated_at?->toAtomString()];}
 private function direct(string $slug):?array{try{$s=Solution::publiclyVisible()->where('slug',$slug)->first();return $s?$this->transform($this->load($s),false):null;}catch(Throwable){return null;}} private function link(?string $label,?string $url):?array{return $label&&$url&&PublicLink::isSafeUrl($url)?['label'=>$label,'url'=>$url]:null;}
}
