<?php
namespace App\Domain\Industries;
use App\Models\{Industry,IndustryCategory}; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str; use Illuminate\Validation\ValidationException;
final class IndustryManager
{
 public function save(array $data,?Industry $industry,int $userId):Industry{return DB::transaction(function()use($data,$industry,$userId){$industry??=new Industry;$data['updated_by']=$userId;if(!$industry->exists){$data['created_by']=$userId;$data['status']='draft';$data['display_order']=(int)Industry::max('display_order')+1;}else{unset($data['status']);}$industry->fill($data)->save();$this->normalize();return $industry;});}
 public function publish(Industry $s):void{$this->requireContent($s);DB::transaction(fn()=>$s->update(['status'=>'published','published_at'=>now(),'scheduled_for'=>null,'archived_at'=>null]));} public function schedule(Industry $s,string $utc):void{$this->requireContent($s);$s->update(['status'=>'scheduled','scheduled_for'=>$utc,'published_at'=>null,'archived_at'=>null]);} public function unpublish(Industry $s):void{$s->update(['status'=>'draft','published_at'=>null,'scheduled_for'=>null,'archived_at'=>null]);}
 public function archive(Industry $s):void{$d=app(IndustryDependencyInspector::class)->inspect($s);if($d['blocked'])throw ValidationException::withMessages(['industry'=>'Resolve active navigation, homepage, and incoming industry references before archiving.']);$s->update(['status'=>'archived','archived_at'=>now(),'published_at'=>null,'scheduled_for'=>null]);} public function restore(Industry $s):void{$s->update(['status'=>'draft','archived_at'=>null,'published_at'=>null,'scheduled_for'=>null]);}
 public function duplicate(Industry $s,int $userId):Industry{return DB::transaction(function()use($s,$userId){$copy=$s->replicate(['status','published_at','scheduled_for','archived_at','created_by','updated_by']);$copy->title.=' (Copy)';$copy->slug=$this->uniqueSlug($s->slug.'-copy');$copy->status='draft';$copy->published_at=$copy->scheduled_for=$copy->archived_at=null;$copy->created_by=$copy->updated_by=$userId;$copy->display_order=(int)Industry::max('display_order')+1;$copy->save();foreach(['challenges','outcomes','needs','useCases'] as $relation){$s->{$relation}()->each(fn($child)=>$copy->{$relation}()->create($child->only($child->getFillable())));}return $copy;});}
 public function move(Industry $s,string $direction):void{DB::transaction(function()use($s,$direction){$peer=Industry::where('display_order',$direction==='up'?'<':'>',$s->display_order)->orderBy('display_order',$direction==='up'?'desc':'asc')->first();if($peer){$a=$s->display_order;$s->update(['display_order'=>$peer->display_order]);$peer->update(['display_order'=>$a]);}$this->normalize();});}
 public function uniqueSlug(string $base):string{$base=Str::slug(Str::lower($base))?:'industry';$slug=$base;for($i=2;Industry::where('slug',$slug)->exists();$i++)$slug=Str::limit($base,150,'')."-$i";return $slug;} private function normalize():void{Industry::orderBy('display_order')->orderBy('id')->get()->each(fn($s,$i)=>$s->display_order===$i+1?null:$s->updateQuietly(['display_order'=>$i+1]));} private function requireContent(Industry $s):void{if(!trim($s->title)||!trim($s->short_description))throw ValidationException::withMessages(['industry'=>'A title and short description are required before publication.']);}
 public function saveCategory(array $data,?IndustryCategory $category=null):IndustryCategory{return DB::transaction(function()use($data,$category){$category??=new IndustryCategory;if(!$category->exists)$data['display_order']=(int)IndustryCategory::max('display_order')+1;$category->fill($data)->save();$this->normalizeCategories();return $category;});} public function moveCategory(IndustryCategory $c,string $direction):void{DB::transaction(function()use($c,$direction){$p=IndustryCategory::where('display_order',$direction==='up'?'<':'>',$c->display_order)->orderBy('display_order',$direction==='up'?'desc':'asc')->first();if($p){$a=$c->display_order;$c->update(['display_order'=>$p->display_order]);$p->update(['display_order'=>$a]);}$this->normalizeCategories();});} private function normalizeCategories():void{IndustryCategory::orderBy('display_order')->orderBy('id')->get()->each(fn($c,$i)=>$c->display_order===$i+1?null:$c->updateQuietly(['display_order'=>$i+1]));}
}
