<?php
use App\Domain\PublicChrome\{NavigationManager,PublicAssetPath,PublicChrome,PublicChromeCache,PublicLink}; use App\Models\{BrandingSetting,FooterColumn,FooterSetting,HeaderSetting,NavigationItem,NavigationMenu,SocialLink,User,WebsiteSetting}; use Illuminate\Support\Facades\{Cache,Http};
use function Pest\Laravel\mock; use Illuminate\Validation\ValidationException;
function installedAdministrator(array $overrides=[]):User{return User::factory()->create(array_merge(['is_active'=>true,'email_verified_at'=>now()],$overrides));}
function phaseSevenInstalled():void{mock(\App\Domain\Installation\InstalledState::class)->shouldReceive('isInstalled')->andReturnTrue();}
test('public chrome admin routes require authentication',function(){phaseSevenInstalled();foreach(['/website/branding','/website/header','/website/navigation','/website/footer'] as $path)$this->get($path)->assertRedirect('/login');});
test('admin routes require active administrator and installed state',function(){$inactive=installedAdministrator(['is_active'=>false]);$this->actingAs($inactive)->get('/website/branding')->assertRedirect('/login');$active=installedAdministrator();$this->actingAs($active)->get('/website/branding')->assertRedirect();phaseSevenInstalled();$this->actingAs($active)->get('/website/branding')->assertSuccessful()->assertSee('noindex, nofollow',false);});
test('branding saves singleton and validates safe paths colors and alt text',function(){phaseSevenInstalled();$this->actingAs(installedAdministrator());$valid=['site_logo_path'=>'images/logo.webp','logo_alt_text'=>'Company logo','primary_color'=>'#123ABC','show_product_attribution'=>1];$this->put(route('admin.branding.update'),$valid)->assertSessionHasNoErrors();expect(BrandingSetting::count())->toBe(1);$this->put(route('admin.branding.update'),$valid+['site_logo_path'=>'../secret.png'])->assertSessionHasErrors('site_logo_path');foreach(['/etc/passwd','https://example.com/logo.png'] as $path)$this->put(route('admin.branding.update'),['site_logo_path'=>$path,'logo_alt_text'=>'Logo'])->assertSessionHasErrors('site_logo_path');$this->put(route('admin.branding.update'),['site_logo_path'=>'images/logo.png'])->assertSessionHasErrors('logo_alt_text');$this->put(route('admin.branding.update'),['favicon_path'=>'images/favicon.svg'])->assertSessionHasErrors('favicon_path');$this->put(route('admin.branding.update'),['primary_color'=>'red;display:none'])->assertSessionHasErrors('primary_color');});
test('header disables unsupported controls and rejects unsafe CTA',function(){phaseSevenInstalled();$this->actingAs(installedAdministrator());$this->put(route('admin.header.update'),['show_top_bar'=>1,'sticky_header'=>1,'show_site_name'=>1,'show_search'=>1,'show_language_switcher'=>1,'show_primary_cta'=>1,'primary_cta_label'=>'Go','primary_cta_url'=>'javascript:alert(1)','primary_cta_target'=>'_self','primary_cta_style'=>'primary'])->assertSessionHasErrors('primary_cta_url');$this->put(route('admin.header.update'),['show_top_bar'=>1,'sticky_header'=>1,'show_site_name'=>1,'show_primary_cta'=>1,'primary_cta_label'=>'Go','primary_cta_url'=>'/contact','primary_cta_target'=>'_self','primary_cta_style'=>'primary'])->assertSessionHasNoErrors();expect(HeaderSetting::first()->show_search)->toBeFalse()->and(HeaderSetting::first()->show_language_switcher)->toBeFalse();});
test('menu locations are unique and protected routes are never approved',function(){NavigationMenu::create(['name'=>'Primary','location'=>'primary']);expect(fn()=>NavigationMenu::create(['name'=>'Other','location'=>'primary']))->toThrow(Throwable::class)->and(PublicLink::isApprovedRoute('admin.branding.edit'))->toBeFalse()->and(PublicLink::isApprovedRoute('home'))->toBeTrue();});
test('URL policy rejects unsafe schemes credentials and accepts public links',function(){foreach(['javascript:alert(1)','data:text/html,x','file:///etc/passwd','https://user:pass@example.com'] as $url)expect(PublicLink::isSafeUrl($url))->toBeFalse();expect(PublicLink::isSafeUrl('/about'))->toBeTrue()->and(PublicLink::isSafeUrl('https://example.com/about'))->toBeTrue();});
test('navigation hierarchy enforces menu parent cycle depth and limits',function(){$manager=app(NavigationManager::class);$a=NavigationMenu::create(['name'=>'A','location'=>'primary']);$b=NavigationMenu::create(['name'=>'B','location'=>'legal']);$root=$manager->save($a,['label'=>'Root','link_type'=>'disabled','target'=>'_self','display_order'=>0]);$child=$manager->save($a,['parent_id'=>$root->id,'label'=>'Child','link_type'=>'disabled','target'=>'_self','display_order'=>0]);$grand=$manager->save($a,['parent_id'=>$child->id,'label'=>'Grand','link_type'=>'disabled','target'=>'_self','display_order'=>0]);expect(fn()=>$manager->save($a,['parent_id'=>$grand->id,'label'=>'Too deep','link_type'=>'disabled','target'=>'_self','display_order'=>0]))->toThrow(ValidationException::class)->and(fn()=>$manager->save($a,['parent_id'=>$root->id,'label'=>'Cycle','link_type'=>'disabled','target'=>'_self','display_order'=>0],$grand))->toThrow(ValidationException::class);$other=$manager->save($b,['label'=>'Other','link_type'=>'disabled','target'=>'_self','display_order'=>0]);expect(fn()=>$manager->save($a,['parent_id'=>$other->id,'label'=>'Wrong','link_type'=>'disabled','target'=>'_self','display_order'=>0]))->toThrow(ValidationException::class)->and(fn()=>$manager->delete($root))->toThrow(ValidationException::class)->and(fn()=>$manager->deleteMenu($a))->toThrow(ValidationException::class);});
test('model changes invalidate versioned public cache',function(){Cache::put(PublicChromeCache::PRIMARY,['stale'],60);NavigationMenu::create(['name'=>'Primary','location'=>'primary']);expect(Cache::has(PublicChromeCache::PRIMARY))->toBeFalse();});
test('public shell renders configured structured safe chrome',function(){WebsiteSetting::create(['site_name'=>'Acme','legal_name'=>'Acme Ltd','primary_email'=>'hi@example.com','country_code'=>'GB','timezone'=>'UTC','default_locale'=>'en','site_url'=>'https://example.com']);BrandingSetting::create(['site_logo_path'=>'images/logo.webp','logo_alt_text'=>'Acme logo']);HeaderSetting::create(['show_top_bar'=>true]);$menu=NavigationMenu::create(['name'=>'Primary','location'=>'primary']);$parent=NavigationItem::create(['navigation_menu_id'=>$menu->id,'label'=>'Company','link_type'=>'disabled','target'=>'_self','display_order'=>1,'depth'=>1]);NavigationItem::create(['navigation_menu_id'=>$menu->id,'parent_id'=>$parent->id,'label'=>'External','link_type'=>'url','url'=>'https://example.org','target'=>'_blank','display_order'=>1,'depth'=>2]);Http::fake();$this->get('/')->assertSuccessful()->assertSee('images/logo.webp',false)->assertSee('aria-expanded',false)->assertSee('Company')->assertSee('rel="noopener noreferrer"',false)->assertSee('Mobile primary navigation',false);Http::assertNothingSent();});
test('missing chrome safely falls back without caching secrets',function(){$data=app(PublicChrome::class)->data();expect($data['navigation'][0]['label'])->toBe('Home');$serialized=json_encode(Cache::get(PublicChromeCache::PRIMARY));expect($serialized)->not->toContain('request_token','signed_entitlement','APP_KEY');});
test('footer dependency and social validation are safe',function(){phaseSevenInstalled();$this->actingAs(installedAdministrator());$setting=FooterSetting::create();$column=$setting->columns()->create(['title'=>'Company']);$column->links()->create(['label'=>'Home','link_type'=>'route','route_name'=>'home']);$this->delete(route('admin.footer.columns.destroy',$column))->assertSessionHasErrors('column');$this->post(route('admin.footer.social.store'),['platform'=>'script','label'=>'Bad','url'=>'javascript:x','icon'=>'raw-svg','display_order'=>0])->assertSessionHasErrors();});
test('phase seven introduces no roles permissions homepage modules or Gumroad',function(){$files=implode('',array_map('file_get_contents',array_merge(glob(app_path('**/*.php'))?:[],glob(resource_path('views/admin/public-chrome/*.blade.php'))?:[])));expect($files)->not->toContain('Spatie\\Permission','Gumroad','homepage_sections');});
