<x-layouts.app :title="$definition['label']" :breadcrumbs="[['label' => 'Website'], ['label' => 'Homepage', 'url' => route('admin.homepage.edit')], ['label' => $definition['label']]]">
    <x-admin.page-header :title="$definition['label']" :description="$definition['description']" />
    @include('admin.public-chrome._messages')
    <div class="mt-6 grid gap-6 xl:grid-cols-2">
        <x-admin.card><form method="POST" action="{{ route('admin.homepage.sections.update', $record) }}" class="grid gap-5">@csrf @method('PUT')<x-admin.validation-summary />
            <x-admin.checkbox name="is_enabled" label="Enable this section" :checked="old('is_enabled', $record->is_enabled)" />
            <div class="grid gap-5 sm:grid-cols-2"><x-admin.form-input name="eyebrow" label="Eyebrow" :value="old('eyebrow', $record->eyebrow)" /><x-admin.form-input name="heading" label="Heading" :value="old('heading', $record->heading)" /></div>
            <x-admin.textarea name="description" label="Description">{{ old('description', $record->description) }}</x-admin.textarea><x-admin.textarea name="secondary_description" label="Secondary description">{{ old('secondary_description', $record->secondary_description) }}</x-admin.textarea>
            <div class="grid gap-5 sm:grid-cols-2"><x-admin.form-input name="image_path" label="Local image path" :value="old('image_path', $record->image_path)" /><x-admin.form-input name="image_alt" label="Image alt text" :value="old('image_alt', $record->image_alt)" /></div>
            <div class="grid gap-5 sm:grid-cols-2"><x-admin.form-input name="primary_cta_label" label="Primary CTA label" :value="old('primary_cta_label', $record->primary_cta_label)" /><x-admin.form-input name="primary_cta_url" label="Primary CTA URL" :value="old('primary_cta_url', $record->primary_cta_url)" /></div>
            <div class="grid gap-5 sm:grid-cols-2"><x-admin.form-input name="secondary_cta_label" label="Secondary CTA label" :value="old('secondary_cta_label', $record->secondary_cta_label)" /><x-admin.form-input name="secondary_cta_url" label="Secondary CTA URL" :value="old('secondary_cta_url', $record->secondary_cta_url)" /></div>
            <div class="grid gap-5 sm:grid-cols-2"><x-admin.select name="background_style" label="Background" :options="array_combine(\App\Domain\Homepage\HomepageSectionRegistry::BACKGROUNDS, \App\Domain\Homepage\HomepageSectionRegistry::BACKGROUNDS)" :value="$record->background_style" /><x-admin.select name="content_width" label="Content width" :options="array_combine(\App\Domain\Homepage\HomepageSectionRegistry::WIDTHS, \App\Domain\Homepage\HomepageSectionRegistry::WIDTHS)" :value="$record->content_width" /></div>
            <x-admin.form-footer><x-admin.primary-button>Save section draft</x-admin.primary-button></x-admin.form-footer>
        </form></x-admin.card>
        @if($definition['item_type'])<x-admin.card><h2 class="text-lg font-bold">Add {{ strtolower($definition['label']) }} item</h2><p class="mt-1 text-sm text-slate-600">Maximum {{ $definition['maximum'] }}. All content is plain text; paths must reference local assets.</p><form method="POST" action="{{ route('admin.homepage.items.store', $record) }}" class="mt-5 grid gap-4">@csrf
            @if($definition['secondary_item_type'])<x-admin.select name="item_type" label="Item type" :options="[$definition['item_type'] => 'Hero slide', $definition['secondary_item_type'] => 'Hero tab']" />@endif
            @if($record->section_key === 'featured_products')<x-admin.select name="product_id" label="Canonical product (optional)" :options="[''=>'Keep homepage-only preview']+$products->mapWithKeys(fn($product)=>[$product->id=>$product->title.' ('.ucfirst($product->status).')'])->all()" />@endif
            @if($record->section_key === 'featured_solutions')<x-admin.select name="solution_id" label="Canonical solution (optional)" :options="[''=>'Keep homepage-only preview']+$solutions->mapWithKeys(fn($solution)=>[$solution->id=>$solution->title.' ('.ucfirst($solution->status).')'])->all()" />@endif
            <x-admin.form-input name="title" label="Title / name / question" required /><x-admin.textarea name="description" label="Description / quote / answer"></x-admin.textarea>
            <div class="grid gap-4 sm:grid-cols-2"><x-admin.form-input name="organization" label="Organization / designation" /><x-admin.select name="icon" label="Icon" :options="['' => 'None'] + array_combine(\App\Domain\Homepage\HomepageSectionRegistry::ICONS, \App\Domain\Homepage\HomepageSectionRegistry::ICONS)" /></div>
            <div class="grid gap-4 sm:grid-cols-2"><x-admin.form-input name="image_path" label="Local image / logo path" /><x-admin.form-input name="image_alt" label="Image alt text" /></div>
            @if($definition['item_type'] === 'hero_slide')<x-admin.form-input name="mobile_image_path" label="Local mobile image path" />@endif
            <div class="grid gap-4 sm:grid-cols-2"><x-admin.form-input name="primary_cta_label" label="CTA / website label" /><x-admin.form-input name="primary_cta_url" label="CTA / website URL" /></div>
            @if($definition['item_type'] === 'statistic')<div class="grid gap-4 sm:grid-cols-3"><x-admin.form-input name="prefix" label="Prefix" /><x-admin.form-input name="value" label="Value" required /><x-admin.form-input name="suffix" label="Suffix" /></div>@endif
            @if($definition['item_type'] === 'testimonial')<x-admin.form-input name="rating" type="number" min="1" max="5" label="Rating (optional, 1–5)" />@endif
            @if($definition['item_type'] === 'insight')<x-admin.form-input name="published_on" type="date" label="Published date (optional)" />@endif
            <div class="grid gap-4 sm:grid-cols-2"><x-admin.form-input name="display_order" type="number" min="0" max="999" value="0" label="Display order" required /><x-admin.checkbox name="is_active" label="Active" checked /></div>
            <x-admin.primary-button>Add item</x-admin.primary-button>
        </form></x-admin.card>@endif
    </div>
    @if($definition['item_type'])<section class="mt-8" aria-labelledby="items-heading"><h2 id="items-heading" class="text-xl font-bold">Current items</h2><div class="mt-4 grid gap-3">@forelse($record->items as $item)<x-admin.card><div class="flex items-center justify-between gap-4"><div><p class="font-semibold">{{ $item->title }}</p><p class="text-sm text-slate-600">Order {{ $item->display_order }} · {{ $item->is_active ? 'Active' : 'Inactive' }}</p></div><form method="POST" action="{{ route('admin.homepage.items.destroy', [$record, $item]) }}" onsubmit="return confirm('Delete this homepage item? Referenced files will remain.')">@csrf @method('DELETE')<x-admin.danger-button>Delete</x-admin.danger-button></form></div></x-admin.card>@empty<x-admin.empty-state title="No items" description="Add truthful homepage content above. No sample records are inserted." />@endforelse</div></section>@endif
</x-layouts.app>
