<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('article_categories', function (Blueprint $table) {
            $table->id(); $table->string('name', 160); $table->string('slug', 160)->unique(); $table->text('description')->nullable(); $table->unsignedSmallInteger('display_order')->default(0); $table->boolean('is_active')->default(true)->index(); $table->timestamps();
        });
        Schema::create('articles', function (Blueprint $table) {
            $table->id(); $table->foreignId('article_category_id')->nullable()->constrained()->restrictOnDelete(); $table->string('title', 180); $table->string('slug', 180)->unique(); $table->string('eyebrow', 120)->nullable(); $table->text('excerpt'); $table->longText('body'); $table->string('featured_image_path')->nullable(); $table->string('featured_image_alt', 180)->nullable(); $table->string('author_name', 160)->nullable(); $table->unsignedSmallInteger('reading_time_minutes')->nullable(); $table->string('status', 20)->default('draft')->index(); $table->boolean('is_featured')->default(false)->index(); $table->unsignedSmallInteger('display_order')->default(0); $table->timestamp('published_at')->nullable()->index(); $table->timestamp('scheduled_for')->nullable()->index(); $table->timestamp('archived_at')->nullable()->index(); $table->string('meta_title', 70)->nullable(); $table->string('meta_description', 170)->nullable(); $table->string('canonical_url', 2048)->nullable(); $table->string('og_title', 70)->nullable(); $table->string('og_description', 200)->nullable(); $table->string('og_image_path')->nullable(); $table->boolean('robots_index')->default(true); $table->boolean('robots_follow')->default(true); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); $table->index(['status', 'archived_at', 'display_order']);
        });
        Schema::create('case_studies', function (Blueprint $table) {
            $table->id(); $table->foreignId('client_id')->nullable()->constrained()->restrictOnDelete(); $table->foreignId('testimonial_id')->nullable()->constrained()->restrictOnDelete(); $table->string('title', 180); $table->string('slug', 180)->unique(); $table->string('eyebrow', 120)->nullable(); $table->text('short_description'); $table->longText('challenge'); $table->longText('solution'); $table->longText('outcome'); $table->string('featured_image_path')->nullable(); $table->string('featured_image_alt', 180)->nullable(); $table->date('project_date')->nullable(); $table->string('project_duration_text', 120)->nullable(); $table->string('location_text', 160)->nullable(); $table->string('status', 20)->default('draft')->index(); $table->boolean('is_featured')->default(false)->index(); $table->unsignedSmallInteger('display_order')->default(0); $table->timestamp('published_at')->nullable()->index(); $table->timestamp('scheduled_for')->nullable()->index(); $table->timestamp('archived_at')->nullable()->index(); $table->string('primary_cta_label', 80)->nullable(); $table->string('primary_cta_url', 2048)->nullable(); $table->string('meta_title', 70)->nullable(); $table->string('meta_description', 170)->nullable(); $table->string('canonical_url', 2048)->nullable(); $table->string('og_title', 70)->nullable(); $table->string('og_description', 200)->nullable(); $table->string('og_image_path')->nullable(); $table->boolean('robots_index')->default(true); $table->boolean('robots_follow')->default(true); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); $table->index(['status', 'archived_at', 'display_order']);
        });
        Schema::create('case_study_metrics', function (Blueprint $table) { $table->id(); $table->foreignId('case_study_id')->constrained()->cascadeOnDelete(); $table->string('label', 160); $table->string('value', 160); $table->string('prefix', 30)->nullable(); $table->string('suffix', 30)->nullable(); $table->text('description')->nullable(); $table->unsignedSmallInteger('display_order')->default(0); $table->boolean('is_active')->default(true); $table->timestamps(); });
        Schema::create('case_study_highlights', function (Blueprint $table) { $table->id(); $table->foreignId('case_study_id')->constrained()->cascadeOnDelete(); $table->string('title', 160); $table->text('description'); $table->string('icon', 40)->nullable(); $table->unsignedSmallInteger('display_order')->default(0); $table->boolean('is_active')->default(true); $table->timestamps(); });
        Schema::create('faq_groups', function (Blueprint $table) { $table->id(); $table->string('title', 160); $table->string('slug', 160)->unique(); $table->text('description')->nullable(); $table->unsignedSmallInteger('display_order')->default(0); $table->boolean('is_active')->default(true)->index(); $table->timestamps(); });
        Schema::create('faqs', function (Blueprint $table) { $table->id(); $table->foreignId('faq_group_id')->nullable()->constrained()->restrictOnDelete(); $table->string('question', 300); $table->text('answer'); $table->string('status', 20)->default('draft')->index(); $table->boolean('is_featured')->default(false); $table->unsignedSmallInteger('display_order')->default(0); $table->timestamp('published_at')->nullable()->index(); $table->timestamp('scheduled_for')->nullable()->index(); $table->timestamp('archived_at')->nullable()->index(); $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $table->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete(); $table->timestamps(); });
        foreach (['article_article' => ['article_id', 'articles', 'related_article_id', 'articles'], 'article_solution' => ['article_id', 'articles', 'solution_id', 'solutions'], 'article_product' => ['article_id', 'articles', 'product_id', 'products'], 'article_industry' => ['article_id', 'articles', 'industry_id', 'industries'], 'article_capability' => ['article_id', 'articles', 'capability_id', 'capabilities'], 'article_page' => ['article_id', 'articles', 'page_id', 'pages'], 'case_study_solution' => ['case_study_id', 'case_studies', 'solution_id', 'solutions'], 'case_study_product' => ['case_study_id', 'case_studies', 'product_id', 'products'], 'case_study_industry' => ['case_study_id', 'case_studies', 'industry_id', 'industries'], 'case_study_capability' => ['case_study_id', 'case_studies', 'capability_id', 'capabilities'], 'case_study_page' => ['case_study_id', 'case_studies', 'page_id', 'pages']] as $name => [$left, $leftTable, $right, $rightTable]) {
            Schema::create($name.'_relations', function (Blueprint $table) use ($left, $leftTable, $right, $rightTable) { $table->id(); $table->foreignId($left)->constrained($leftTable)->cascadeOnDelete(); $table->foreignId($right)->constrained($rightTable)->restrictOnDelete(); $table->unsignedSmallInteger('display_order')->default(0); $table->unique([$left, $right]); });
        }
        Schema::table('homepage_items', function (Blueprint $table) { $table->foreignId('article_id')->nullable()->after('homepage_section_id')->constrained()->restrictOnDelete(); $table->foreignId('faq_id')->nullable()->after('article_id')->constrained()->restrictOnDelete(); });
    }

    public function down(): void
    {
        Schema::table('homepage_items', function (Blueprint $table) { $table->dropConstrainedForeignId('faq_id'); $table->dropConstrainedForeignId('article_id'); });
        foreach (['case_study_page_relations','case_study_capability_relations','case_study_industry_relations','case_study_product_relations','case_study_solution_relations','article_page_relations','article_capability_relations','article_industry_relations','article_product_relations','article_solution_relations','article_article_relations','faqs','faq_groups','case_study_highlights','case_study_metrics','case_studies','articles','article_categories'] as $table) { Schema::dropIfExists($table); }
    }
};
