<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void {
Schema::create('product_categories',function(Blueprint $t){$t->id();$t->string('name',120);$t->string('slug',120)->unique();$t->text('description')->nullable();$t->unsignedSmallInteger('display_order')->default(1);$t->boolean('is_active')->default(true)->index();$t->timestamps();});
Schema::create('products',function(Blueprint $t){$t->id();$t->foreignId('product_category_id')->nullable()->constrained()->restrictOnDelete();$t->string('title',160);$t->string('slug',160)->unique();$t->string('eyebrow',120)->nullable();$t->string('short_description',500);$t->text('overview')->nullable();$t->text('problem_statement')->nullable();$t->text('value_proposition')->nullable();$t->string('icon',40)->nullable();$t->string('featured_image_path')->nullable();$t->string('featured_image_alt',160)->nullable();$t->string('hero_style',30)->default('standard');$t->string('template',30)->default('standard');$t->string('status',20)->default('draft')->index();$t->boolean('is_featured')->default(false)->index();$t->unsignedSmallInteger('display_order')->default(1);$t->timestamp('published_at')->nullable()->index();$t->timestamp('scheduled_for')->nullable()->index();$t->timestamp('archived_at')->nullable()->index();foreach(['primary','secondary','demo'] as $c){$t->string($c.'_cta_label',80)->nullable();$t->string($c.'_cta_url',2048)->nullable();}$t->string('documentation_url',2048)->nullable();$t->string('meta_title',70)->nullable();$t->string('meta_description',170)->nullable();$t->string('canonical_url',2048)->nullable();$t->string('og_title',70)->nullable();$t->string('og_description',200)->nullable();$t->string('og_image_path')->nullable();$t->boolean('robots_index')->default(true);$t->boolean('robots_follow')->default(true);$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['product_category_id','display_order']);});
Schema::create('product_editions',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('name',120);$t->string('slug',120);$t->string('short_description',500)->nullable();$t->string('badge_text',40)->nullable();$t->string('edition_type',30);$t->unsignedSmallInteger('display_order')->default(1);$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['product_id','slug']);$t->index(['product_id','display_order']);});
Schema::create('product_feature_groups',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('title',160);$t->text('description')->nullable();$t->unsignedSmallInteger('display_order')->default(1);$t->boolean('is_active')->default(true);$t->timestamps();$t->index(['product_id','display_order']);});
Schema::create('product_features',function(Blueprint $t){$t->id();$t->foreignId('product_feature_group_id')->constrained()->cascadeOnDelete();$t->string('title',160);$t->text('description')->nullable();$t->string('icon',40)->nullable();$t->unsignedSmallInteger('display_order')->default(1);$t->boolean('is_active')->default(true);$t->timestamps();$t->index(['product_feature_group_id','display_order']);});
foreach(['product_benefits','product_use_cases'] as $n){Schema::create($n,function(Blueprint $t)use($n){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('title',160);$t->text('description')->nullable($n === 'product_benefits');if($n==='product_use_cases')$t->string('sector',120)->nullable();$t->string('icon',40)->nullable();$t->unsignedSmallInteger('display_order')->default(1);$t->boolean('is_active')->default(true);$t->timestamps();$t->index(['product_id','display_order']);});}
Schema::create('product_specifications',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('label',160);$t->text('value');$t->string('group_name',120)->nullable();$t->unsignedSmallInteger('display_order')->default(1);$t->boolean('is_active')->default(true);$t->timestamps();$t->index(['product_id','display_order']);});
Schema::create('product_gallery_items',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('image_path');$t->string('image_alt',160);$t->string('caption',500)->nullable();$t->unsignedSmallInteger('display_order')->default(1);$t->boolean('is_active')->default(true);$t->timestamps();$t->index(['product_id','display_order']);});
Schema::create('product_integrations',function(Blueprint $t){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->string('name',160);$t->text('description')->nullable();$t->string('logo_path')->nullable();$t->string('logo_alt',160)->nullable();$t->string('website_url',2048)->nullable();$t->unsignedSmallInteger('display_order')->default(1);$t->boolean('is_active')->default(true);$t->timestamps();$t->index(['product_id','display_order']);});
foreach([['product_relations','related_product_id','products'],['product_solution_relations','solution_id','solutions'],['product_page_relations','page_id','pages']] as [$n,$key,$target]){Schema::create($n,function(Blueprint $t)use($key,$target){$t->id();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->foreignId($key)->constrained($target)->restrictOnDelete();$t->unsignedSmallInteger('display_order')->default(1);$t->timestamps();$t->unique(['product_id',$key]);});}
Schema::table('homepage_items',fn(Blueprint $t)=>$t->foreignId('product_id')->nullable()->constrained()->restrictOnDelete());Schema::table('navigation_items',function(Blueprint $t){$t->foreignId('product_id')->nullable()->constrained()->restrictOnDelete();$t->index(['link_type','product_id']);});}
public function down():void{Schema::table('navigation_items',fn(Blueprint $t)=>$t->dropConstrainedForeignId('product_id'));Schema::table('homepage_items',fn(Blueprint $t)=>$t->dropConstrainedForeignId('product_id'));foreach(['product_page_relations','product_solution_relations','product_relations','product_integrations','product_use_cases','product_gallery_items','product_specifications','product_benefits','product_features','product_feature_groups','product_editions','products','product_categories'] as $n)Schema::dropIfExists($n);}};