@props(['siteName', 'navigation' => []])
<header class="sticky top-0 z-40 border-b border-public-border bg-white/95 shadow-xs backdrop-blur" x-data="publicNavigation" data-public-header>
<div class="public-container flex min-h-20 items-center justify-between gap-5"><a href="{{ route('home') }}" class="flex min-w-0 items-center gap-3 rounded-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-public-focus" aria-label="{{ $siteName }} home"><span class="flex size-10 shrink-0 items-center justify-center rounded-lg bg-public-primary font-bold text-white" aria-hidden="true">N</span><span class="truncate text-lg font-bold tracking-tight text-public-navy">{{ $siteName }}</span></a>
<nav class="hidden items-center gap-1 xl:flex" aria-label="Primary navigation">@foreach($navigation as $item) @if(isset($item['route']))<a href="{{ route($item['route']) }}" @class(['public-nav-link', 'bg-blue-50 text-public-primary' => request()->routeIs($item['route'])]) @if(request()->routeIs($item['route'])) aria-current="page" @endif>{{ $item['label'] }}</a>@else<span class="public-nav-disabled" aria-disabled="true" title="Coming soon">{{ $item['label'] }}<span class="sr-only"> — Coming soon</span></span>@endif @endforeach</nav>
<div class="hidden xl:block"><x-public.button disabled size="sm">Book a Demo<span class="sr-only"> — Coming soon</span></x-public.button></div><button x-ref="opener" x-on:click="open()" type="button" class="public-icon-button xl:hidden" aria-label="Open navigation" aria-controls="mobile-navigation" :aria-expanded="navigationOpen.toString()"><span aria-hidden="true" class="text-2xl">☰</span></button></div>
<div x-cloak x-show="navigationOpen" x-transition.opacity class="fixed inset-0 z-50 bg-slate-950/60 xl:hidden" x-on:click.self="close()" aria-hidden="true"></div>
<aside id="mobile-navigation" x-cloak x-show="navigationOpen" x-transition:enter="transition ease-out duration-200" x-transition:enter-start="translate-x-full" x-transition:enter-end="translate-x-0" x-transition:leave="transition ease-in duration-150" x-transition:leave-start="translate-x-0" x-transition:leave-end="translate-x-full" x-ref="drawer" class="fixed inset-y-0 end-0 z-[60] w-[min(90vw,24rem)] overflow-y-auto bg-white p-6 shadow-2xl xl:hidden" role="dialog" aria-modal="true" aria-label="Mobile navigation" tabindex="-1">
<div class="flex items-center justify-between gap-4 border-b border-public-border pb-5"><strong class="text-lg text-public-navy">Menu</strong><button x-ref="close" x-on:click="close()" type="button" class="public-icon-button" aria-label="Close navigation"><span aria-hidden="true" class="text-2xl">×</span></button></div><nav class="mt-5 grid gap-2" aria-label="Mobile primary navigation">
@foreach($navigation as $item) @if(isset($item['route']))<a href="{{ route($item['route']) }}" class="public-mobile-link" @if(request()->routeIs($item['route'])) aria-current="page" @endif>{{ $item['label'] }}</a>@elseif(isset($item['children']))<details class="group rounded-lg border border-public-border"><summary class="flex min-h-12 cursor-pointer items-center justify-between px-4 font-semibold text-public-secondary">{{ $item['label'] }}<span class="text-xs text-public-muted">Coming soon</span></summary><ul class="border-t border-public-border p-2">@foreach($item['children'] as $child)<li><span class="flex min-h-11 items-center rounded-md px-3 text-sm text-public-muted" aria-disabled="true">{{ $child }}<span class="sr-only"> — Coming soon</span></span></li>@endforeach</ul></details>@else<span class="public-mobile-link text-public-muted" aria-disabled="true">{{ $item['label'] }}<span class="ms-auto text-xs">Coming soon</span></span>@endif @endforeach</nav><div class="mt-6"><x-public.button disabled class="w-full">Book a Demo<span class="sr-only"> — Coming soon</span></x-public.button></div></aside>
</header>
