<x-layouts.public-site :settings="$settings" :site-name="$siteName" :legal-name="$legalName" :navigation="$navigation" :chrome="$chrome" :page-title="$product['og_title']" :description="$product['og_description']" :canonical="$product['canonical_url'] ?: rtrim($canonical,'/').'/products/'.$product['slug']" :robots="$product['robots']" :image="$product['og_image'] ? asset($product['og_image']) : null">
@if($preview)<div class="bg-amber-100 px-4 py-3 text-center font-semibold text-amber-950" role="status">Preview Mode — this product is not being served from the public cache.</div>@endif
<article><x-public.section><x-public.breadcrumb :items="[['label'=>'Home','url'=>route('home')],['label'=>'Products','url'=>route('products.index')],['label'=>$product['title']]]"/><div class="mt-8 grid items-center gap-8 lg:grid-cols-2"><div><p class="text-sm font-semibold uppercase tracking-wider text-blue-700">{{ $product['eyebrow'] ?: ($product['category']['name'] ?? 'Product') }}</p><h1 class="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">{{ $product['title'] }}</h1><p class="mt-5 text-lg text-slate-600">{{ $product['short_description'] }}</p><div class="mt-6 flex flex-wrap gap-3">@foreach($product['ctas'] as $cta)<x-public.button :href="$cta['url']">{{ $cta['label'] }}</x-public.button>@endforeach @if($product['documentation_url'])<x-public.button :href="$product['documentation_url']" variant="secondary">Documentation</x-public.button>@endif</div></div>@if($product['image'])<x-public.image :src="asset($product['image'])" :alt="$product['image_alt']" class="rounded-2xl"/>@endif</div></x-public.section>
@foreach(['overview'=>'Overview','problem_statement'=>'The problem','value_proposition'=>'Value proposition'] as $key=>$heading)@if($product[$key])<x-public.section><x-public.section-heading :title="$heading"/><p class="mt-5 max-w-4xl whitespace-pre-line text-slate-700">{{ $product[$key] }}</p></x-public.section>@endif @endforeach
@if($product['editions'])<x-public.section><x-public.section-heading title="Editions"/><div class="mt-6 grid gap-5 md:grid-cols-2 lg:grid-cols-3">@foreach($product['editions'] as $edition)<x-public.card><h3 class="text-xl font-bold">{{ $edition['title'] }}</h3>@if($edition['badge'])<p class="mt-2 text-sm font-semibold">{{ $edition['badge'] }}</p>@endif<p class="mt-3 text-slate-600">{{ $edition['description'] }}</p></x-public.card>@endforeach</div></x-public.section>@endif
@if($product['feature_groups'])<x-public.section><x-public.section-heading title="Features"/><div class="mt-6 grid gap-6 lg:grid-cols-2">@foreach($product['feature_groups'] as $group)<section class="rounded-2xl border p-6"><h3 class="text-xl font-bold">{{ $group['title'] }}</h3><p class="mt-2 text-slate-600">{{ $group['description'] }}</p><ul class="mt-4 grid gap-3">@foreach($group['features'] as $feature)<li><strong>{{ $feature['title'] }}</strong><p>{{ $feature['description'] }}</p></li>@endforeach</ul></section>@endforeach</div></x-public.section>@endif
@foreach(['benefits'=>'Benefits','use_cases'=>'Use cases'] as $key=>$heading)@if($product[$key])<x-public.section><x-public.section-heading :title="$heading"/><div class="mt-6 grid gap-5 md:grid-cols-2 lg:grid-cols-3">@foreach($product[$key] as $item)<x-public.card><h3 class="font-bold">{{ $item['title'] }}</h3><p class="mt-2 text-slate-600">{{ $item['description'] }}</p></x-public.card>@endforeach</div></x-public.section>@endif @endforeach
@if($product['specifications'])<x-public.section><x-public.section-heading title="Specifications"/><dl class="mt-6 divide-y rounded-xl border">@foreach($product['specifications'] as $spec)<div class="grid gap-2 p-4 sm:grid-cols-3"><dt class="font-semibold">{{ $spec['label'] }}</dt><dd class="sm:col-span-2">{{ $spec['value'] }}</dd></div>@endforeach</dl></x-public.section>@endif
@if($product['gallery'])<x-public.section><x-public.section-heading title="Gallery"/><div class="mt-6 grid gap-5 md:grid-cols-2">@foreach($product['gallery'] as $image)<figure><x-public.image :src="asset($image['image'])" :alt="$image['alt']" class="rounded-xl"/>@if($image['caption'])<figcaption class="mt-2 text-sm text-slate-600">{{ $image['caption'] }}</figcaption>@endif</figure>@endforeach</div></x-public.section>@endif
@if($product['integrations'])<x-public.section><x-public.section-heading title="Integrations"/><div class="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4">@foreach($product['integrations'] as $integration)<x-public.card>@if($integration['logo'])<x-public.image :src="asset($integration['logo'])" :alt="$integration['logo_alt']"/>@endif<h3 class="mt-3 font-bold">{{ $integration['name'] }}</h3><p>{{ $integration['description'] }}</p>@if($integration['url'])<a class="mt-3 inline-block font-semibold text-blue-700" href="{{ $integration['url'] }}" rel="noopener">Website</a>@endif</x-public.card>@endforeach</div></x-public.section>@endif
@foreach(['related_products'=>'Related products','related_solutions'=>'Related solutions','related_pages'=>'Related pages'] as $key=>$heading)@if($product[$key])<x-public.section><x-public.section-heading :title="$heading"/><div class="mt-6 grid gap-4 md:grid-cols-3">@foreach($product[$key] as $related)<x-public.card><h3 class="font-bold"><a href="{{ $related['url'] }}">{{ $related['title'] }}</a></h3>@if(isset($related['description']))<p class="mt-2">{{ $related['description'] }}</p>@endif</x-public.card>@endforeach</div></x-public.section>@endif @endforeach
</article></x-layouts.public-site>
