<?php
use App\Domain\Products\{ProductDependencyInspector,ProductManager,ProductRelationManager}; use App\Models\{HomepageItem,NavigationItem,NavigationMenu,Product,ProductCategory,Solution,User,WebsiteSetting}; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\Cache; use Illuminate\Validation\ValidationException;
use function Pest\Laravel\mock;
uses(RefreshDatabase::class);
function productAdmin():User{return User::factory()->create(['is_active'=>true]);}
function productsInstalled():void{mock(\App\Domain\Installation\InstalledState::class)->shouldReceive('isInstalled')->andReturnTrue();}
it('protects product admin and preview routes',function(){productsInstalled();$p=Product::factory()->create();$this->get('/content/products')->assertRedirect('/login');$this->get(route('admin.products.create'))->assertRedirect('/login');$this->get(route('admin.products.preview',$p))->assertRedirect('/login');});
it('requires an active administrator',function(){productsInstalled();$user=User::factory()->create(['is_active'=>false]);$this->actingAs($user)->get(route('admin.products.index'))->assertForbidden();});
it('allows anonymous index and only visible details',function(){$draft=Product::factory()->create();$future=Product::factory()->scheduled()->create();$due=Product::factory()->scheduled(now()->subMinute())->create();$published=Product::factory()->published()->create();$archived=Product::factory()->archived()->create();$this->get(route('products.index'))->assertSuccessful();$this->get(route('products.show',$draft->slug))->assertNotFound();$this->get(route('products.show',$future->slug))->assertNotFound();$this->get(route('products.show',$due->slug))->assertSuccessful()->assertSee($due->title);$this->get(route('products.show',$published->slug))->assertSuccessful();$this->get(route('products.show',$archived->slug))->assertNotFound();});
it('normalizes slugs and validates product allow lists and unsafe input',function(){productsInstalled();$this->actingAs(productAdmin())->post(route('admin.products.store'),['title'=>'Naxora','slug'=>'My Product','short_description'=>'Safe summary','template'=>'standard','hero_style'=>'standard'])->assertRedirect();$this->assertDatabaseHas('products',['slug'=>'my-product','status'=>'draft']);$payload=['title'=>'Bad','slug'=>'create','short_description'=>'Summary','template'=>'arbitrary','hero_style'=>'arbitrary','primary_cta_label'=>'Run','primary_cta_url'=>'javascript:alert(1)','featured_image_path'=>'https://example.com/a.jpg','featured_image_alt'=>'A'];$this->post(route('admin.products.store'),$payload)->assertSessionHasErrors(['slug','template','hero_style','primary_cta_url','featured_image_path']);});
it('manages unique categories and contiguous ordering',function(){productsInstalled();$admin=productAdmin();$this->actingAs($admin)->post(route('admin.products.categories.store'),['name'=>'Platforms','slug'=>'Platforms','is_active'=>'1'])->assertRedirect();$this->post(route('admin.products.categories.store'),['name'=>'Duplicate','slug'=>'platforms'])->assertSessionHasErrors('slug');expect(ProductCategory::first()->display_order)->toBe(1);});
it('enforces edition uniqueness type and maximum',function(){productsInstalled();$admin=productAdmin();$p=Product::factory()->create();$route=fn()=>route('admin.products.children.store',[$p,'editions']);$this->actingAs($admin)->post($route(),['name'=>'Standard','slug'=>'standard','edition_type'=>'standard','is_active'=>1])->assertRedirect();$this->post($route(),['name'=>'Duplicate','slug'=>'standard','edition_type'=>'standard'])->assertSessionHasErrors('slug');$this->post($route(),['name'=>'Bad','slug'=>'bad','edition_type'=>'priced'])->assertSessionHasErrors('edition_type');for($i=2;$i<=8;$i++)$p->editions()->create(['name'=>"E$i",'slug'=>"e-$i",'edition_type'=>'custom','display_order'=>$i]);$this->post($route(),['name'=>'Too many','slug'=>'too-many','edition_type'=>'custom'])->assertSessionHasErrors('editions');});
it('rejects self relations and archived targets',function(){$p=Product::factory()->create();expect(fn()=>app(ProductRelationManager::class)->sync($p,[$p->id],[],[]))->toThrow(ValidationException::class);$archived=Product::factory()->archived()->create();expect(fn()=>app(ProductRelationManager::class)->sync($p,[$archived->id],[],[]))->toThrow(ValidationException::class);});
it('performs lifecycle scheduling duplication and preview safely',function(){productsInstalled();$admin=productAdmin();WebsiteSetting::query()->create(['singleton_key'=>1,'site_name'=>'Naxora','site_url'=>'https://example.test','timezone'=>'Africa/Lagos']);$p=Product::factory()->create(['overview'=>'Preserved']);$m=app(ProductManager::class);$m->publish($p);expect($p->refresh()->status)->toBe('published');$m->unpublish($p);expect($p->refresh()->overview)->toBe('Preserved');$m->schedule($p,'2026-08-07 12:00:00');expect($p->refresh()->scheduled_for->timezone('UTC')->format('Y-m-d H:i:s'))->toBe('2026-08-07 12:00:00');$copy=$m->duplicate($p,$admin->id);expect($copy->status)->toBe('draft')->and($copy->slug)->not->toBe($p->slug)->and($copy->published_at)->toBeNull();$this->actingAs($admin)->get(route('admin.products.preview',$p))->assertSuccessful()->assertSee('Preview Mode')->assertHeader('X-Robots-Tag','noindex, nofollow')->assertHeader('Cache-Control','no-store, private, max-age=0');});
it('blocks archive for active navigation and homepage dependencies',function(){$p=Product::factory()->create();$menu=NavigationMenu::create(['name'=>'Primary','location'=>'primary','is_active'=>true]);NavigationItem::create(['navigation_menu_id'=>$menu->id,'label'=>'Product','link_type'=>'product','product_id'=>$p->id,'target'=>'_self','display_order'=>1,'depth'=>0,'is_active'=>true]);expect(app(ProductDependencyInspector::class)->inspect($p)['blocked'])->toBeTrue();expect(fn()=>app(ProductManager::class)->archive($p))->toThrow(ValidationException::class);});
it('includes indexable products in sitemap and excludes private products',function(){$public=Product::factory()->published()->create();$private=Product::factory()->create();$this->get(route('sitemap'))->assertSuccessful()->assertSee('/products/'.$public->slug,false)->assertDontSee('/products/'.$private->slug,false);});
it('does not expose commerce or entitlement data in public product output',function(){$p=Product::factory()->published()->create();$this->get(route('products.show',$p->slug))->assertSuccessful()->assertDontSee('checkout')->assertDontSee('signed_entitlement')->assertDontSee('request_token');});
