<?php
namespace App\Models;
use App\Models\Concerns\InvalidatesSolutions; use Illuminate\Database\Eloquent\Builder; use Illuminate\Database\Eloquent\Factories\HasFactory; use Illuminate\Database\Eloquent\Model; use Illuminate\Database\Eloquent\Relations\{BelongsTo,BelongsToMany,HasMany};
class Solution extends Model
{
 use HasFactory,InvalidatesSolutions;
 protected $fillable=['solution_category_id','title','slug','eyebrow','short_description','overview','challenge_text','approach_text','outcome_text','icon','featured_image_path','featured_image_alt','hero_style','template','status','is_featured','display_order','published_at','scheduled_for','archived_at','primary_cta_label','primary_cta_url','secondary_cta_label','secondary_cta_url','meta_title','meta_description','canonical_url','og_title','og_description','og_image_path','robots_index','robots_follow','created_by','updated_by'];
 protected function casts():array{return ['is_featured'=>'boolean','robots_index'=>'boolean','robots_follow'=>'boolean','published_at'=>'datetime','scheduled_for'=>'datetime','archived_at'=>'datetime'];}
 public function category():BelongsTo{return $this->belongsTo(SolutionCategory::class,'solution_category_id');} public function features():HasMany{return $this->hasMany(SolutionFeature::class)->orderBy('display_order')->orderBy('id');} public function benefits():HasMany{return $this->hasMany(SolutionBenefit::class)->orderBy('display_order')->orderBy('id');} public function capabilities():HasMany{return $this->hasMany(SolutionCapability::class)->orderBy('display_order')->orderBy('id');} public function processSteps():HasMany{return $this->hasMany(SolutionProcessStep::class)->orderBy('display_order')->orderBy('id');} public function useCases():HasMany{return $this->hasMany(SolutionUseCase::class)->orderBy('display_order')->orderBy('id');}
 public function relatedSolutions():BelongsToMany{return $this->belongsToMany(self::class,'solution_relations','solution_id','related_solution_id')->withPivot('display_order')->orderByPivot('display_order');} public function relatedPages():BelongsToMany{return $this->belongsToMany(Page::class,'solution_page_relations')->withPivot('display_order')->orderByPivot('display_order');} public function navigationItems():HasMany{return $this->hasMany(NavigationItem::class);} public function homepageItems():HasMany{return $this->hasMany(HomepageItem::class);}
 public function scopePubliclyVisible(Builder $query):Builder{return $query->whereNull('archived_at')->whereNotNull('short_description')->where(function(Builder $q):void{$q->where(fn(Builder $p)=>$p->where('status','published')->whereNotNull('published_at')->where('published_at','<=',now()))->orWhere(fn(Builder $s)=>$s->where('status','scheduled')->whereNotNull('scheduled_for')->where('scheduled_for','<=',now()));});}
 public function isPubliclyVisible():bool{return $this->archived_at===null&&(($this->status==='published'&&$this->published_at?->lte(now()))||($this->status==='scheduled'&&$this->scheduled_for?->lte(now())))&&trim((string)$this->short_description)!=='';}
}
