<?php
namespace App\Http\Controllers\Admin;
use App\Domain\Products\{ProductCache,ProductRegistry}; use App\Domain\PublicChrome\{PublicAssetPath,PublicLink}; use App\Http\Controllers\Controller; use App\Models\{Product,ProductBenefit,ProductEdition,ProductFeature,ProductFeatureGroup,ProductGalleryItem,ProductIntegration,ProductSpecification,ProductUseCase}; use Illuminate\Database\Eloquent\Model; use Illuminate\Http\{RedirectResponse,Request}; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str; use Illuminate\Validation\Rule; use Illuminate\Validation\ValidationException;
class ProductChildController extends Controller
{
 private const MAP=['editions'=>[ProductEdition::class,'editions'],'feature-groups'=>[ProductFeatureGroup::class,'featureGroups'],'benefits'=>[ProductBenefit::class,'benefits'],'specifications'=>[ProductSpecification::class,'specifications'],'gallery'=>[ProductGalleryItem::class,'galleryItems'],'use-cases'=>[ProductUseCase::class,'useCases'],'integrations'=>[ProductIntegration::class,'integrations']];
 public function store(Request $r,Product $product,string $type):RedirectResponse{$relation=self::MAP[$type][1];if($product->{$relation}()->count()>=ProductRegistry::LIMITS[$type])throw ValidationException::withMessages([$type=>'Maximum item count reached.']);$data=$this->validateData($r,$type,$product);$data['display_order']=(int)$product->{$relation}()->max('display_order')+1;$product->{$relation}()->create($data);ProductCache::forget($product->id);return back()->with('status','Product item added.');}
 public function update(Request $r,Product $product,string $type,int $child):RedirectResponse{$model=$this->child($product,$type,$child);$model->update($this->validateData($r,$type,$product,$model));ProductCache::forget($product->id);return back()->with('status','Product item updated.');}
 public function destroy(Product $product,string $type,int $child):RedirectResponse{$this->child($product,$type,$child)->delete();$this->normalize($product,$type);ProductCache::forget($product->id);return back();}
 public function move(Request $r,Product $product,string $type,int $child):RedirectResponse{$direction=$r->validate(['direction'=>['required','in:up,down']])['direction'];$model=$this->child($product,$type,$child);$relation=self::MAP[$type][1];DB::transaction(function()use($product,$relation,$model,$direction){$peer=$product->{$relation}()->where('display_order',$direction==='up'?'<':'>',$model->display_order)->orderBy('display_order',$direction==='up'?'desc':'asc')->first();if($peer){$x=$model->display_order;$model->update(['display_order'=>$peer->display_order]);$peer->update(['display_order'=>$x]);}});$this->normalize($product,$type);ProductCache::forget($product->id);return back();}
 public function storeFeature(Request $r,Product $product,ProductFeatureGroup $group):RedirectResponse{abort_unless($group->product_id===$product->id,404);if($group->features()->count()>=20)throw ValidationException::withMessages(['features'=>'Maximum feature count reached.']);$data=$r->validate(['title'=>['required','string','max:160'],'description'=>['nullable','string','max:4000'],'icon'=>['nullable',Rule::in(ProductRegistry::ICONS)],'is_active'=>['boolean']]);$data['is_active']=$r->boolean('is_active');$data['display_order']=(int)$group->features()->max('display_order')+1;$group->features()->create($data);ProductCache::forget($product->id);return back();}
 public function destroyFeature(Product $product,ProductFeatureGroup $group,ProductFeature $feature):RedirectResponse{abort_unless($group->product_id===$product->id&&$feature->product_feature_group_id===$group->id,404);$feature->delete();ProductCache::forget($product->id);return back();}
 private function child(Product $p,string $type,int $id):Model{$relation=self::MAP[$type][1];return $p->{$relation}()->findOrFail($id);} private function normalize(Product $p,string $type):void{$relation=self::MAP[$type][1];$p->{$relation}()->orderBy('display_order')->orderBy('id')->get()->each(fn($x,$i)=>$x->updateQuietly(['display_order'=>$i+1]));}
 private function validateData(Request $r,string $type,Product $p,?Model $model=null):array{$r->merge(['is_active'=>$r->boolean('is_active')]);$common=['is_active'=>['boolean']];$rules=match($type){'editions'=>['name'=>['required','string','max:120'],'slug'=>['required','regex:/^[a-z0-9]+(?:-[a-z0-9]+)*$/',Rule::unique('product_editions')->where('product_id',$p->id)->ignore($model)],'short_description'=>['nullable','string','max:500'],'badge_text'=>['nullable','string','max:40'],'edition_type'=>['required',Rule::in(ProductRegistry::EDITION_TYPES)]],'feature-groups'=>['title'=>['required','string','max:160'],'description'=>['nullable','string','max:4000']],'benefits'=>['title'=>['required','string','max:160'],'description'=>['nullable','string','max:4000'],'icon'=>['nullable',Rule::in(ProductRegistry::ICONS)]],'specifications'=>['label'=>['required','string','max:160'],'value'=>['required','string','max:2000'],'group_name'=>['nullable','string','max:120']],'gallery'=>['image_path'=>['required','string','max:255',fn($a,$v,$f)=>PublicAssetPath::isSafe($v)?:$f('Use an approved local raster image path.')],'image_alt'=>['required','string','max:160'],'caption'=>['nullable','string','max:500']],'use-cases'=>['title'=>['required','string','max:160'],'description'=>['required','string','max:4000'],'sector'=>['nullable','string','max:120'],'icon'=>['nullable',Rule::in(ProductRegistry::ICONS)]],'integrations'=>['name'=>['required','string','max:160'],'description'=>['nullable','string','max:4000'],'logo_path'=>['nullable','string','max:255',fn($a,$v,$f)=>PublicAssetPath::isSafe($v)?:$f('Use an approved local raster image path.')],'logo_alt'=>['nullable','required_with:logo_path','string','max:160'],'website_url'=>['nullable','string','max:2048',fn($a,$v,$f)=>$v&&!PublicLink::isSafeUrl($v)?$f('Use a safe URL.'):null]],default=>abort(404)};$data=$r->validate($rules+$common);if($type==='editions')$data['slug']=Str::slug(Str::lower($data['slug']));return $data;}
}
