<?php
namespace App\Http\Controllers\Admin;
use App\Domain\PublicChrome\{NavigationManager,PublicLink}; use App\Http\Controllers\Controller; use App\Http\Requests\PublicChrome\{BrandingRequest,FooterRequest,HeaderRequest}; use App\Models\{BrandingSetting,FooterColumn,FooterLink,FooterSetting,HeaderSetting,NavigationItem,NavigationMenu,Page,SocialLink}; use Illuminate\Contracts\View\View; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Validation\Rule; use Illuminate\Validation\ValidationException;
class PublicChromeController extends Controller
{
 public function branding():View{return view('admin.public-chrome.branding',['setting'=>BrandingSetting::query()->first()??new BrandingSetting]);}
 public function saveBranding(BrandingRequest $r):RedirectResponse{BrandingSetting::query()->updateOrCreate(['singleton_key'=>1],$r->validated());return back()->with('status','Branding settings saved.');}
 public function header():View{return view('admin.public-chrome.header',['setting'=>HeaderSetting::query()->first()??new HeaderSetting]);}
 public function saveHeader(HeaderRequest $r):RedirectResponse{HeaderSetting::query()->updateOrCreate(['singleton_key'=>1],$r->validated());return back()->with('status','Header settings saved.');}
 public function navigation():View{return view('admin.public-chrome.navigation',['menus'=>NavigationMenu::query()->withCount('items')->orderBy('location')->get()]);}
 public function storeMenu(Request $r):RedirectResponse{$data=$r->validate(['name'=>['required','string','max:120'],'location'=>['required',Rule::in(NavigationMenu::LOCATIONS),Rule::unique('navigation_menus','location')],'description'=>['nullable','string','max:240'],'is_active'=>['boolean']]);$menu=NavigationMenu::query()->create($data);return redirect()->route('admin.navigation.edit',$menu)->with('status','Menu created.');}
 public function editNavigation(NavigationMenu $menu):View{$menu->load(['items'=>fn($q)=>$q->with('page')->withCount('children')->orderBy('depth')->orderBy('display_order')]);return view('admin.public-chrome.navigation-edit',['menu'=>$menu,'pages'=>Page::query()->where('status','!=','archived')->orderBy('title')->get(['id','title','status'])]);}
 public function updateMenu(Request $r,NavigationMenu $menu):RedirectResponse{$menu->update($r->validate(['name'=>['required','string','max:120'],'description'=>['nullable','string','max:240'],'is_active'=>['boolean']]));return back()->with('status','Menu updated.');}
 public function deleteMenu(NavigationMenu $menu,NavigationManager $manager):RedirectResponse{$manager->deleteMenu($menu);return redirect()->route('admin.navigation.index')->with('status','Menu deleted.');}
 public function saveItem(Request $r,NavigationMenu $menu,NavigationManager $manager,?NavigationItem $item=null):RedirectResponse{if($item&&$item->navigation_menu_id!==$menu->id)abort(404);$data=$r->validate(['parent_id'=>['nullable','integer','exists:navigation_items,id'],'label'=>['required','string','max:120'],'link_type'=>['required','in:route,page,url,disabled'],'route_name'=>['nullable','string','max:120'],'page_id'=>['nullable','integer','exists:pages,id'],'url'=>['nullable','string','max:2048'],'target'=>['required','in:_self,_blank'],'description'=>['nullable','string','max:240'],'badge_text'=>['nullable','string','max:40'],'display_order'=>['required','integer','between:0,999'],'is_active'=>['boolean'],'is_featured'=>['boolean'],'opens_mega_menu'=>['boolean']]);if($data['link_type']==='route'&&!PublicLink::isApprovedRoute($data['route_name']??null))throw ValidationException::withMessages(['route_name'=>'Choose an approved existing public route.']);if($data['link_type']==='page'&&!Page::query()->whereKey($data['page_id']??null)->where('status','!=','archived')->exists())throw ValidationException::withMessages(['page_id'=>'Choose a non-archived page.']);if($data['link_type']==='url'&&!PublicLink::isSafeUrl($data['url']??null))throw ValidationException::withMessages(['url'=>'Use a safe relative or HTTP/HTTPS URL without credentials.']);$manager->save($menu,$data,$item);return back()->with('status','Navigation item saved.');}
 public function deleteItem(NavigationMenu $menu,NavigationItem $item,NavigationManager $manager):RedirectResponse{if($item->navigation_menu_id!==$menu->id)abort(404);$manager->delete($item);return back()->with('status','Navigation item deleted.');}
 public function moveItem(NavigationMenu $menu,NavigationItem $item,Request $r,NavigationManager $manager):RedirectResponse{if($item->navigation_menu_id!==$menu->id)abort(404);$manager->move($item,$r->validate(['direction'=>['required','in:up,down']])['direction']);return back()->with('status','Order updated.');}
 public function footer():View{$setting=FooterSetting::query()->with(['columns.links','socialLinks'])->first()??new FooterSetting;return view('admin.public-chrome.footer',compact('setting'));}
 public function saveFooter(FooterRequest $r):RedirectResponse{FooterSetting::query()->updateOrCreate(['singleton_key'=>1],$r->validated());return back()->with('status','Footer settings saved.');}
 public function storeColumn(Request $r):RedirectResponse{$setting=FooterSetting::query()->firstOrCreate(['singleton_key'=>1]);$setting->columns()->create($r->validate(['title'=>['required','string','max:120'],'display_order'=>['required','integer','between:0,999'],'is_active'=>['boolean']]));return back()->with('status','Footer column created.');}
 public function deleteColumn(FooterColumn $column):RedirectResponse{if($column->links()->exists())throw ValidationException::withMessages(['column'=>'Remove links before deleting this column.']);$column->delete();return back()->with('status','Footer column deleted.');}
 public function storeFooterLink(Request $r,FooterColumn $column):RedirectResponse{$data=$r->validate(['label'=>['required','string','max:120'],'link_type'=>['required','in:route,url,disabled'],'route_name'=>['nullable','string'],'url'=>['nullable','string','max:2048'],'target'=>['required','in:_self,_blank'],'display_order'=>['required','integer','between:0,999'],'is_active'=>['boolean']]);if($data['link_type']==='route'&&!PublicLink::isApprovedRoute($data['route_name']??null))throw ValidationException::withMessages(['route_name'=>'Choose an approved public route.']);if($data['link_type']==='url'&&!PublicLink::isSafeUrl($data['url']??null))throw ValidationException::withMessages(['url'=>'Use a safe URL.']);$column->links()->create($data);return back()->with('status','Footer link created.');}
 public function deleteFooterLink(FooterLink $link):RedirectResponse{$link->delete();return back()->with('status','Footer link deleted.');}
 public function storeSocial(Request $r):RedirectResponse{$setting=FooterSetting::query()->firstOrCreate(['singleton_key'=>1]);$data=$r->validate(['platform'=>['required',Rule::in(SocialLink::PLATFORMS)],'label'=>['required','string','max:120'],'url'=>['required','url:http,https','max:2048'],'icon'=>['required',Rule::in(SocialLink::ICONS)],'display_order'=>['required','integer','between:0,999'],'is_active'=>['boolean']]);if(!PublicLink::isSafeUrl($data['url'],false))throw ValidationException::withMessages(['url'=>'Use a safe HTTP/HTTPS URL without credentials.']);$setting->socialLinks()->create($data);return back()->with('status','Social link created.');}
 public function deleteSocial(SocialLink $social):RedirectResponse{$social->delete();return back()->with('status','Social link deleted.');}
}
