<?php
namespace App\Http\Controllers\Admin;
use App\Domain\Solutions\SolutionRegistry; use App\Http\Controllers\Controller; use App\Models\{Solution,SolutionBenefit,SolutionCapability,SolutionFeature,SolutionProcessStep,SolutionUseCase}; use Illuminate\Http\{RedirectResponse,Request}; use Illuminate\Support\Facades\DB; use Illuminate\Validation\Rule; use Illuminate\Validation\ValidationException;
class SolutionChildController extends Controller
{
 private const MAP=['features'=>SolutionFeature::class,'benefits'=>SolutionBenefit::class,'capabilities'=>SolutionCapability::class,'process-steps'=>SolutionProcessStep::class,'use-cases'=>SolutionUseCase::class];
 public function store(Request $r,Solution $solution,string $type):RedirectResponse{$class=$this->class($type);$relation=$this->relation($type);$max=SolutionRegistry::CHILDREN[$relation];if($solution->{$relation}()->count()>=$max)throw ValidationException::withMessages([$type=>"A maximum of $max records is allowed."]);$data=$this->data($r,$type);$data['display_order']=(int)$solution->{$relation}()->max('display_order')+1;$solution->{$relation}()->create($data);return back()->with('status','Structured item added.');}
 public function update(Request $r,Solution $solution,string $type,int $child):RedirectResponse{$model=$this->owned($solution,$type,$child);$model->update($this->data($r,$type));return back()->with('status','Structured item saved.');} public function destroy(Solution $solution,string $type,int $child):RedirectResponse{$this->owned($solution,$type,$child)->delete();$this->normalize($solution,$type);return back()->with('status','Leaf item removed.');} public function move(Request $r,Solution $solution,string $type,int $child):RedirectResponse{$model=$this->owned($solution,$type,$child);$direction=$r->validate(['direction'=>['required','in:up,down']])['direction'];$class=$this->class($type);DB::transaction(function()use($model,$class,$direction,$solution,$type){$peer=$class::where('solution_id',$solution->id)->where('display_order',$direction==='up'?'<':'>',$model->display_order)->orderBy('display_order',$direction==='up'?'desc':'asc')->first();if($peer){$a=$model->display_order;$model->update(['display_order'=>$peer->display_order]);$peer->update(['display_order'=>$a]);}$this->normalize($solution,$type);});return back();}
 private function data(Request $r,string $type):array{return $r->validate(['title'=>['required','string','max:160'],'description'=>[$type==='benefits'?'nullable':'required','string','max:5000'],'sector'=>[$type==='use-cases'?'nullable':'prohibited','string','max:120'],'icon'=>['nullable',Rule::in(SolutionRegistry::ICONS)],'is_active'=>['boolean']]);} private function class(string $type):string{return self::MAP[$type]??abort(404);} private function relation(string $type):string{return match($type){'process-steps'=>'processSteps','use-cases'=>'useCases',default=>$type};} private function owned(Solution $s,string $type,int $id){return $this->class($type)::where('solution_id',$s->id)->findOrFail($id);} private function normalize(Solution $s,string $type):void{$this->class($type)::where('solution_id',$s->id)->orderBy('display_order')->orderBy('id')->get()->each(fn($v,$i)=>$v->updateQuietly(['display_order'=>$i+1]));}
}
