<?php
namespace App\Http\Controllers\Admin;
use App\Domain\Installation\WebsiteSettings; use App\Domain\Solutions\{SolutionDependencyInspector,SolutionManager,SolutionRegistry,SolutionRelationManager,SolutionViewData}; use App\Http\Controllers\{Controller,PublicSiteController}; use App\Http\Requests\Solutions\SaveSolutionRequest; use App\Models\{Page,Solution,SolutionCategory}; use Illuminate\Contracts\View\View; use Illuminate\Http\{RedirectResponse,Request,Response}; use Illuminate\Support\Carbon; use Illuminate\Support\Str; use Illuminate\Validation\Rule;
class SolutionController extends Controller
{
 public function index(Request $r):View{$f=$r->validate(['search'=>['nullable','string','max:160'],'category'=>['nullable','integer'],'status'=>['nullable',Rule::in(['draft','published','scheduled','archived'])],'featured'=>['nullable','in:0,1'],'archived'=>['nullable','in:with,only,without'],'sort'=>['nullable','in:title,updated_at,published_at,display_order'],'direction'=>['nullable','in:asc,desc']]);$q=Solution::with('category')->withCount(['navigationItems','homepageItems','relatedSolutions'])->when($f['search']??null,fn($q,$v)=>$q->where(fn($q)=>$q->where('title','like',"%$v%")->orWhere('slug','like',"%$v%")))->when($f['category']??null,fn($q,$v)=>$q->where('solution_category_id',$v))->when($f['status']??null,fn($q,$v)=>$q->where('status',$v))->when(isset($f['featured']),fn($q)=>$q->where('is_featured',(bool)$f['featured']));if(($f['archived']??'without')==='only')$q->whereNotNull('archived_at');elseif(($f['archived']??'without')==='without')$q->whereNull('archived_at');$solutions=$q->orderBy($f['sort']??'display_order',$f['direction']??'asc')->paginate(20)->withQueryString();return view('admin.solutions.index',compact('solutions','f')+['categories'=>SolutionCategory::orderBy('display_order')->get()]);}
 public function create():View{return $this->editor(new Solution);} public function store(SaveSolutionRequest $r,SolutionManager $m):RedirectResponse{$s=$m->save($r->validated(),null,$r->user()->id);return redirect()->route('admin.solutions.edit',$s)->with('status','Draft solution created.');} public function edit(Solution $solution):View{return $this->editor($solution);} public function update(SaveSolutionRequest $r,Solution $solution,SolutionManager $m):RedirectResponse{$m->save($r->validated(),$solution,$r->user()->id);return back()->with('status','Solution saved as draft content without changing publication state.');}
 private function editor(Solution $s):View{if($s->exists)$s->load(['features','benefits','capabilities','processSteps','useCases','relatedSolutions','relatedPages']);return view('admin.solutions.editor',['solution'=>$s,'categories'=>SolutionCategory::where('is_active',true)->orderBy('display_order')->get(),'templates'=>SolutionRegistry::TEMPLATES,'heroes'=>SolutionRegistry::HERO_STYLES,'icons'=>SolutionRegistry::ICONS,'solutions'=>Solution::whereKeyNot($s->id)->whereNull('archived_at')->orderBy('title')->get(),'pages'=>Page::whereNull('archived_at')->orderBy('title')->get(),'dependencies'=>$s->exists?app(SolutionDependencyInspector::class)->inspect($s):null]);}
 public function publish(Solution $solution,SolutionManager $m):RedirectResponse{$m->publish($solution);return back()->with('status','Solution published.');} public function schedule(Request $r,Solution $solution,SolutionManager $m):RedirectResponse{$v=$r->validate(['scheduled_for'=>['required','date']]);$tz=app(WebsiteSettings::class)->current()?->timezone?:'UTC';$m->schedule($solution,Carbon::parse($v['scheduled_for'],$tz)->utc()->toDateTimeString());return back()->with('status','Solution scheduled.');} public function unpublish(Solution $solution,SolutionManager $m):RedirectResponse{$m->unpublish($solution);return back()->with('status','Solution returned to draft.');} public function archive(Solution $solution,SolutionManager $m):RedirectResponse{$m->archive($solution);return back()->with('status','Solution archived.');} public function restore(Solution $solution,SolutionManager $m):RedirectResponse{$m->restore($solution);return back()->with('status','Solution restored to draft.');} public function duplicate(Request $r,Solution $solution,SolutionManager $m):RedirectResponse{$copy=$m->duplicate($solution,$r->user()->id);return redirect()->route('admin.solutions.edit',$copy)->with('status','Draft duplicate created.');} public function move(Solution $solution,string $direction,SolutionManager $m):RedirectResponse{$m->move($solution,$direction);return back();}
 public function relations(Request $r,Solution $solution,SolutionRelationManager $m):RedirectResponse{$d=$r->validate(['related_solution_ids'=>['array','max:6'],'related_solution_ids.*'=>['integer','distinct','exists:solutions,id'],'related_page_ids'=>['array','max:6'],'related_page_ids.*'=>['integer','distinct','exists:pages,id']]);$m->sync($solution,$d['related_solution_ids']??[],$d['related_page_ids']??[]);return back()->with('status','Relations saved.');}
 public function preview(Request $r,Solution $solution,SolutionViewData $data):Response{$response=response()->view('solutions.show',['solution'=>$data->preview($solution),'preview'=>true]+app(PublicSiteController::class)->sharedViewData($r));return $response->header('Cache-Control','no-store, private, max-age=0')->header('X-Robots-Tag','noindex, nofollow');}
 public function categories():View{return view('admin.solutions.categories',['categories'=>SolutionCategory::withCount('solutions')->orderBy('display_order')->get()]);} public function storeCategory(Request $r,SolutionManager $m):RedirectResponse{$d=$this->categoryData($r);$m->saveCategory($d);return back()->with('status','Category created.');} public function updateCategory(Request $r,SolutionCategory $category,SolutionManager $m):RedirectResponse{$m->saveCategory($this->categoryData($r,$category),$category);return back()->with('status','Category updated.');} public function moveCategory(SolutionCategory $category,string $direction,SolutionManager $m):RedirectResponse{$m->moveCategory($category,$direction);return back();} private function categoryData(Request $r,?SolutionCategory $c=null):array{$r->merge(['slug'=>Str::slug(Str::lower((string)$r->input('slug'))),'is_active'=>$r->boolean('is_active')]);return $r->validate(['name'=>['required','string','max:120'],'slug'=>['required','regex:/^[a-z0-9]+(?:-[a-z0-9]+)*$/',Rule::unique('solution_categories')->ignore($c)],'description'=>['nullable','string','max:2000'],'is_active'=>['boolean']]);}
}
